import { ability, Boss, detail, Discover, Korok, MakeTOD, Section, Shrine, ShrineBlessing, ShrineDoubleSword, split, step, Tower, VariableChange, Warp } from "../create";
import { gale, cps, txt, fury, emy, important, v, npc } from "../types";
import { wb } from "../windbomb";

export const ForgottenTemple = [
	Section("FORGOTTEN TEMPLE"),
	ability(step(gale()), {gale: 1}),
	Korok("N47", "Confetti", "Top of lab"),
	step(wb(cps)("N + NE")),
	Korok("N32", "Race", "SQ"),
	ShrineBlessing("Taloh O'ah"),
	split("-"),

	step(wb(cps)("E> Turn")),
	Korok("N40", "Lift Rock Blocked", "Under slab"),
	step(wb(cps)("<N Turn + N midair")),
	Korok("N25", "Boulder Golf", "Bomb + STS"),
	step(wb(cps)("N> Turn")),
	"Start flower chase",
	Korok("Z62", "Rock Circle", "During flower chase"),
	Korok("Z61", "Flower Chase"),
	step(wb(cps)("N> Turn + N midair")),
	Korok("Z59", "Flower Chase", "Start in forest"),
	step(wb(cps)("<N to hinox")),
	Korok("Z58", "Balloon", "In cave"),
	ability(Boss("Blue Hinox", fury()), {fury: 3}),
	step(wb(cps)("<W Turn to stone")),
	"Activate Shai Yota",
	Korok("Z56", "Basketball", "On stone"),
	step(wb(cps)("SE")),
	VariableChange({tail: 3}),
	detail(
		emy("3 Lizalfos"),
		txt(v("tail"),"/45. Can kill silver lizalfos if need.")),
	important("CHECK 45 TAILS"),
	important("CHECK 45 OPALS"),
	"Drop down",
	Korok("Z57", "Lift Rock Blocked", "Under slab"),
	step(wb(cps)("<W Turn")),
	Korok("N12", "Rock Circle"),
	step(wb(cps)("W> Turn")),
	Korok("Z55", "Lift Rock"),
	step(wb(cps)("W")),
	Korok("Z54", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("S> Turn")),
	Korok("N14", "Rock Circle"),
	step(wb(cps)("<N Turn")),
	Korok("Z51", "Rock Circle"),
	step(wb(cps)("N>")),
	Shrine("Rucco Maag"),
	split("-"),

	step(wb(cps)("E>")),
	Korok("Z53", "Flower Chase", "In cave"),
	Korok("Z52", "Lift Rock Blocked", "Under leaves"),
	step(wb(cps)("<E")),
	Korok("Z45", "Light Chase"),
	step(wb(cps)("E Turn")),
	npc("Kass"),
	"SQ to shrine",
	ShrineBlessing("Shai Yota"),
	split("-"),

	step(wb(cps)("W>")),
	Korok("Z46", "Block Puzzle"),
	step(wb(cps)("NE")),
	Korok("Z36", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("E + W + W")),
	Korok("Z35", "Lift Rock Blocked", "Under rubble"),
	ability(step(gale()," + ", wb(cps)("NE + <N")), {gale: 1}),
	Korok("Z28", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("<<E Turn")),
	Korok("Z10", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("NW")),
	Korok("Z09", "Lily Pads"),
	step(wb(cps)("W. Turn")),
	Korok("A56", "Light Chase"),
	step(wb(cps)("<<W Turn")),
	Korok("A57", "Confetti", "Top of tree"),
	step(wb(cps)("N> Turn")),
	ShrineDoubleSword("Ke'nai Shakah"),
	split("-"),

	Warp("Shada Naw"),
	split("-"),
    
	step(wb(cps)("S. Turn")),
	Korok("H44", "Balloon", "In cave"),
	step(wb(cps)("S> midair")),
	Korok("H46", "Ice Block"),
	step(wb(cps)("SE")),
	Korok("H48", "Lift Rock", "On ledge"),
	step(wb(cps)("N High DEFUSE")),
	"Start race",
	wb(cps)("SE DEFUSE"),
	detail(
		Korok("H50", "Balloon", "Middle of river"),
		"Shoot both balloons then finish race"),
	Korok("H47", "Balloon", "End of river"),
	Korok("H49", "Race", "Run finish race"),
	step(wb(cps)("NE")),
	Korok("H45", "Ice Block"),
	step(wb(cps)("S")),
	Korok("H56", "Flower Chase", "Across bridge"),
	step(wb(cps)("NE")),
	Korok("H51", "Lift Rock", "Ledge down the camp"),
	step(wb(cps)("E> Turn")),
	Shrine("Gee Ha'rah"),
	split("-"),

	step(wb(cps)("N + S + E")),
	Korok("H57", "Snowball Golf"),
	step(wb(cps)("<<W Turn")),
	ShrineBlessing("Lanno Kooh"),
	split("-"),

	step(Korok("H64", "Lift Rock", "Behind shrine")),
	"Swim out",
	wb(cps)("<E Turn"),
	Korok("H61", "Lift Rock", "Peak"),
	step(wb(cps)("E>>")),
	Tower("Hebra Tower", "98.12%"),
	split("-"),

	step("SQ ", cps(".E")),
	Discover("Pondo's Lodge"),
	MakeTOD("9pm", "Make Night"),
	step(wb(cps)("S DT")),
	Korok("R03", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("<E Turn")),
	Discover("Maritta Exchange Ruins"),
	step(wb(cps)("<E Turn")),
	npc("Talk to Group of 3"),
	npc("Talk to 3 guys each"),
	step(wb(cps)("<E Turn")),
	Korok("K17", "Jump Fence", "Summon Horse"),
	step("Ride ",cps("N"), " to stalnox"),
	ability(Boss("Stalnox", txt("GEB + ", fury())), {fury: 3}),
	step(wb(cps)(".W Turn")),
	Korok("K15", "Lift Rock", "On pillar"),
	step(wb(cps)("W")),
	Korok("H63", "Lift Rock", "Ledge"),
	step(wb(cps)("<E Turn")),
	Korok("K13", "Lift Rock Blocked", "Under rubble"),
	step("SQ ", cps("S")),
	Korok("K14", "Lift Rock (Door)"),
	ability(step(gale(), " to entrance"), {gale: 1}),
	step("BLSS to end"),
	Korok("K09", "Lift Rock", "Behind statue"),
	ShrineBlessing("Rona Kachta"),
	split("-"),
];