import { Boss, Discover, emy, fury, Item, Koroks, Npc, rne, SnapElite, SPLIT, txt, Warp, WindbombStepCps } from "../../engine";

export const LetterQuest = [
	Warp("Ruta"),
	SnapElite("Waterblight"),
	{
		text: emy("Waterblight 2"),
		icon: "ruta-plus",
		comment: fury(),
		notes: txt("Equip ", rne("Cryonis/Camera")),
		ability: { fury: 3 },
		type: SPLIT,
		splitPrefix: "{Zora's Domain 2}"
	},
	WindbombStepCps("N Turn"),
	Boss("Blue Hinox", "5 Spin SLAM"),
	Item("6 Lotus"),
	Koroks.Z24,
	WindbombStepCps("SE"),
	Koroks.Z34,
	WindbombStepCps("E>> SQ"),
	Npc("Monument"),
	WindbombStepCps("W"),
	Npc("Monument"),
	"Run to korok",
	Item("4 Lorus"),
	Koroks.Z33,
	WindbombStepCps("N>"),
	Koroks.Z25,
	WindbombStepCps("SQ to monument"),
	Npc("Monument"),
	WindbombStepCps("W> Turn"),
	Npc("Monument"),
	WindbombStepCps("S> Turn"),
	Koroks.Z32,
	WindbombStepCps("S High"),
	Discover("Luto's Crossing"),
	Npc("Monument"),
	WindbombStepCps("W> Super"),
	Npc("Start Letter Quest"),
	WindbombStepCps("N"),
	Koroks.Z23,
	WindbombStepCps("SE"),
	Npc("Monument"),
	Npc("Monument", "Run"),
	Discover("Oren Bridge"),
	WindbombStepCps("S"),
	Npc("Monument"),
	WindbombStepCps("NW"),
	Koroks.Z31,
	WindbombStepCps("NE"),
	"BLSS with letter to end",

	WindbombStepCps("E>> Turn"),
	Boss("Red Hinox", txt("1 Hit SLAM ", fury())).extend({
		ability: { fury: 1 }
	}),
	WindbombStepCps("SQ to rock circle"),
	Koroks.Z41,

];