import { Warp, step, Korok, ShrineDLC, Chest, split, MakeTOD, detail, ability, Boss, VariableChange, Shrine } from "../create";
import { npc, cps, fury, itm, txt, gale, v } from "../types";
import { wb } from "../windbomb";
import { MONUMENT } from "../ZoraDomain1/Z1.4Ruta";

export const ZoraDLC = [
	npc("Hudson Twice"),
	Warp("Sato Koda"),
	step(wb(cps)("N>")),
	Korok("Z04", "Lift Rock", "Peak"),
	step(wb(cps)("E> Turn")),
	Chest("Zora Helm"),
	step(wb(cps)("E")),
	Korok("Z05", "Light Chase"),
	step(wb(cps)("S Turn")),
	"Start Ring Chase",
	...MONUMENT,
	ShrineDLC("Mah Eliya"),
	split("-"),

	step(wb(cps)("<W")),
	Korok("Z08", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("<E TS")),
	Korok("Z17", "Confetti", "Top of ZD"),
	MakeTOD("12pm", "Make 7AM - 8PM"),

	detail(
		npc("Frog Boy Twice"),
		"<4PM near statue. >4PM near Fronk"),
	npc("Luminous Stone Guy"),
	"Run up stairs and jump over",
	npc("Letter Girl"),
	npc("Diving Quest"),
	npc("Hinox Lady Twice"),
	npc("Monument Guy Twice"),
	npc("Kapson"),
	npc("Lynel Lady Twice"),
	step(wb(cps)("E>")),
	Korok("Z18", "Block Puzzle"),
	step(wb(cps)("S")),
	Korok("Z26", "Lift Rock", "Peak"),
	step(wb(cps)("E> Turn")),
	ability(Boss("Luminous Talus", txt(fury(), itm(" Opal"))), {fury: 3}),
	step(wb(cps)("<E")),
	Korok("Z27", "Block Puzzle"),
	step(wb(cps)("N")),
	"Start Flower Chase",
	Korok("Z19", "Boulder Golf", "Magnesis"),
	cps("E."),
	Korok("Z20", "Flower Chase"),
	step(wb(cps)("<N Turn")),
	Korok("A55", "Lift Rock Blocked", "Under Boulder"),
	step(wb(cps)(".N")),
	Korok("A54", "Balloon"),
	step(wb(cps)("<E Turn")),
	Korok("A53", "Match Tree", "Middle"),
	step(wb(cps)("E Turn")),
	Korok("Z07", "Lift Rock", "On pillar"),
	VariableChange({rushroom: 5}),
	detail(
		itm("5 Rushrooms"),
		txt(v("rushroom"), "/55")),
	Korok("Z06", "Lift Rock", "Wood Platform"),
	step(wb(cps)("N")),
	Korok("Z01", "Flower Chase"),
	Shrine("Kah Mael"),
	split("-"),

	MakeTOD("5am", "Make Morning"),
	ability(step(gale(), " + ", wb(cps)("SE")), {gale: 1}),
	ShrineDLC("Kee Dafunia"),
	split("-"),

	Warp("Vah Ruta"),
	split("-"),
];