import { cps, gale, rne, txt, ingredient} from "./strings";
import { wb } from "./windbomb";
import { addExtend, Ingredient, InstructionPacketWithExtend, Tower, Shrine, Korok, ShrineBlessing, ShrineDLC, ShrineDoubleSword, ShrineSword, Memory } from "./creator";
import {  TextLike } from "./types";

const towerHelper = (name: string): (comment?: TextLike)=>InstructionPacketWithExtend => {
	return (comment)=>Tower(name, comment);
};

export const Towers = {
	Plateau: towerHelper("Great Plateau Tower"),
	Central: towerHelper("Central Tower"),
	Lake: towerHelper("Lake Tower"),
	DuelingPeaks: towerHelper("Dueling Peaks Tower"),
	Faron: towerHelper("Faron Tower"),
	Hateno: towerHelper("Hateno Tower"),
	Lanayru: towerHelper("Lanayru Tower"),
	Eldin: towerHelper("Eldin Tower"),
	Woodland: towerHelper("Woodland Tower"),
	Akkala: towerHelper("Akkala Tower"),
	Tabantha: towerHelper("Tabantha Tower"),
	Gerudo: towerHelper("Gerudo Tower"),
	Wasteland: towerHelper("Wasteland Tower"),
	Hebra: towerHelper("Hebra Tower"),
	Ridgeland: towerHelper("Ridgeland Tower"),
};

export const Memories = {
	"LanayruRoad": Memory("Lanayru Road"),
	"SacredGrounds": Memory("Sacred Grounds"),
	"LakeKolomo": Memory("Lake Kolomo"),
	"AncientColumns": Memory("Ancient Columns"),
	"KaraKaraBazaar": Memory("Kara Kara Bazaar"),
	"EldinCanyon": Memory("Eldin Canyon"),
	"IrchPlain": Memory("Irch Plain"),
	"WestNecluda": Memory("West Necluda"),
	"HyruleCastle": Memory("Hyrule Castle"),
	"SpringOfPower": Memory("Spring of Power"),
	"SanidinPark": Memory("Sanidin Park"),
	"HyruleField": Memory("Hyrule Field"),
	"AshSwamp": Memory("Ash Swamp"),
};

const ingredientHelper = (name: string, total: number): (count: number, comment?: TextLike) => InstructionPacketWithExtend=>{
	const variableName = name.replaceAll(" ", "");
	return (count, comment)=>addExtend({
		variableChange: { [variableName]: count },
		...Ingredient(txt(String(count), " ", name), ingredient(variableName, total), comment)
	});
};

export const Materials = {
	SilentPrincess: ingredientHelper("Silent Princess", 19),
	HeartyBass: ingredientHelper("Hearty Bass", 15),
	Beetle: ingredientHelper("Beetle", 15),
	Tail: ingredientHelper("Tail", 45),
	Honey: ingredientHelper("Honey", 16),
	Rushroom: ingredientHelper("Rushroom", 55),
	Dinraal: ingredientHelper("Dinraal", 8),
};

export const Shrines = {
	JaBaij: Shrine("Ja Baij"),
	OmanAu: Shrine("Oman Au"),
	OwaDaim: Shrine("Owa Daim"),
	KehNamut: Shrine("Keh Namut"),

	AkhVaquot: Shrine("Akh Va'quot"),
	BereedaNaag: Shrine("Bereeda Naag"),
	BoshKala: Shrine("Bosh Kala"),
	ChaasQeta: ShrineDoubleSword("Chaas Qeta"),
	DaagChokah: ShrineBlessing("Daag Chokah"),
	DagahKeek: ShrineBlessing("Dagah Keek"),
	DahHesho: ShrineSword("Dah Hesho"),
	DahKaso: ShrineSword("Dah Kaso"),
	DakaTuss: Shrine("Daka Tuss"),
	DaqaKoh: Shrine("Daqa Koh"),
	DaqoChisay: Shrine("Daqo Chisay"),
	DaqoTah: Shrine("Daqo Tah"),
	DilaMaag: ShrineBlessing("Dila Maag"),
	DowNaeh: Shrine("Dow Na'eh"),
	DunbaTaag: Shrine("Dunba Taag"),
	EtsuKorima: ShrineDLC("Etsu Korima"),
	GeeHarah: Shrine("Gee Ha'rah"),
	GomaAsaagh: ShrineDoubleSword("Goma Asaagh"),
	GoraeTorr: ShrineBlessing("Gorae Torr"),
	HaDahamar: Shrine("Ha Dahamar"),
	HawaKoth: Shrine("Hawa Koth"),
	HiaMiu: ShrineDoubleSword("Hia Miu"),
	HilaRao: Shrine("Hila Rao"),
	IshtoSoh: Shrine("Ishto Soh"),
	JeeNoh: Shrine("Jee Noh"),
	JitanSami: ShrineBlessing("Jitan Sa'mi"),
	JolooNah: Shrine("Joloo Nah"),
	KaamYatak: Shrine("Kaam Ya'tak"),
	KahMael: Shrine("Kah Mael"),
	KahOkeo: Shrine("Kah Okeo"),
	KahYah: Shrine("Kah Yah"),
	KamUrog: Shrine("Kam Urog"),
	KamiaOmuna: ShrineDLC("Kamia Omuna"),
	KaoMakagh: Shrine("Ka'o Makagh"),
	KatahChuki: ShrineSword("Katah Chuki"),
	KatosaAug: Shrine("Katosa Aug"),
	KayNoh: Shrine("Kay Noh"),
	KayaWan: Shrine("Kaya Wan"),
	KayraMah: Shrine("Kayra Mah"),
	KeeDafunia: ShrineDLC("Kee Dafunia"),
	KeehaYoog: ShrineBlessing("Keeha Yoog"),
	KeiveTala: ShrineDLC("Keive Tala"),
	KemaKossasa: ShrineDoubleSword("Kema Kossasa"),
	KemaZoos: Shrine("Kema Zoos"),
	KenaiShakah: ShrineDoubleSword("Ke'nai Shakah"),
	KeoRuug: Shrine("Keo Ruug"),
	KetohWawai: ShrineBlessing("Ketoh Wawai"),
	KiahToza: ShrineDLC("Kiah Toza"),
	KihiroMoh: ShrineDLC("Kihiro Moh"),
	KorguChideh: ShrineBlessing("Korgu Chideh"),
	KorshOhu: ShrineBlessing("Korsh O'hu"),
	KuhTakkar: Shrine("Kuh Takkar"),
	KuhnSidajj: ShrineBlessing("Kuhn Sidajj"),
	LaknaRokee: ShrineBlessing("Lakna Rokee"),
	LannoKooh: ShrineBlessing("Lanno Kooh"),
	MaagHalan: ShrineBlessing("Maag Halan"),
	MaagNorah: ShrineBlessing("Maag No'rah"),
	MahEliya: ShrineDLC("Mah Eliya"),
	MakaRah: Shrine("Maka Rah"),
	MezzaLo: Shrine("Mezza Lo"),
	MijahRokee: ShrineDoubleSword("Mijah Rokee"),
	MirroShaz: Shrine("Mirro Shaz"),
	MisaeSuma: ShrineBlessing("Misae Suma"),
	MoaKeet: Shrine("Mo'a Keet"),
	MoggLatan: Shrine("Mogg Latan"),
	MonyaToma: Shrine("Monya Toma"),
	MozoShenno: ShrineDoubleSword("Mozo Shenno"),
	MuwoJeem: ShrineDoubleSword("Muwo Jeem"),
	MyahmAgana: Shrine("Myahm Agana"),
	NamikaOzz: ShrineDoubleSword("Namika Ozz"),
	NeezYohma: Shrine("Ne'ez Yohma"),
	NoeRajee: ShrineDLC("Noe Rajee"),
	NoyaNeha: ShrineSword("Noya Neha"),
	PumaagNitae: ShrineSword("Pumaag Nitae"),
	QazaTokki: ShrineBlessing("Qaza Tokki"),
	QuaRaym: Shrine("Qua Raym"),
	QukahNata: ShrineBlessing("Qukah Nata"),
	RaqaZunzo: ShrineBlessing("Raqa Zunzo"),
	ReeDahee: Shrine("Ree Dahee"),
	RinOyaa: Shrine("Rin Oyaa"),
	RinuHonika: ShrineDLC("Rinu Honika"),
	RitaagZumo: ShrineBlessing("Ritaag Zumo"),
	RohtaChigah: ShrineDLC("Rohta Chigah"),
	RokUwog: Shrine("Rok Uwog"),
	RonaKachta: ShrineBlessing("Rona Kachta"),
	RotaOoh: Shrine("Rota Ooh"),
	RuccoMaag: Shrine("Rucco Maag"),
	RuvoKorbah: ShrineDLC("Ruvo Korbah"),
	SaasKosah: ShrineDoubleSword("Saas Ko'sah"),
	SahDahaj: Shrine("Sah Dahaj"),
	SasaKai: ShrineDoubleSword("Sasa Kai"),
	SatoKoda: ShrineDLC("Sato Koda"),
	ShaGehma: Shrine("Sha Gehma"),
	ShaWarvo: Shrine("Sha Warvo"),
	ShadaNaw: Shrine("Shada Naw"),
	ShaeKatha: ShrineBlessing("Shae Katha"),
	ShaeLoya: Shrine("Shae Loya"),
	ShaeMosah: Shrine("Shae Mo'sah"),
	ShaiUtoh: Shrine("Shai Utoh"),
	ShaiYota: ShrineBlessing("Shai Yota"),
	SharoLun: ShrineDLC("Sharo Lun"),
	SheeVaneer: Shrine("Shee Vaneer"),
	SheeVaneth: Shrine("Shee Vaneth"),
	SheemDagoze: Shrine("Sheem Dagoze"),
	ShehRata: Shrine("Sheh Rata"),
	ShiraGomar: ShrineDLC("Shira Gomar"),
	ShoDantu: Shrine("Sho Dantu"),
	ShodaSah: Shrine("Shoda Sah"),
	ShoqaTatone: ShrineDoubleSword("Shoqa Tatone"),
	ShoraHah: Shrine("Shora Hah"),
	SohKofi: ShrineSword("Soh Kofi"),
	SumaSahma: ShrineBlessing("Suma Sahma"),
	TahMuhl: Shrine("Tah Muhl"),
	TakamaShiri: ShrineDLC("Takama Shiri"),
	TalohNaeg: ShrineSword("Ta'loh Naeg"),
	TalohOah: ShrineBlessing("Taloh O'ah"),
	TawaJinn: ShrineBlessing("Tawa Jinn"),
	TenaKosah: ShrineDoubleSword("Tena Ko'sah"),
	ThoKayu: ShrineBlessing("Tho Kayu"),
	ToQuomo: ShrineBlessing("To Quomo"),
	TohYahsa: Shrine("Toh Yahsa"),
	TotoSah: Shrine("Toto Sah"),
	TuKaloh: ShrineBlessing("Tu Ka'loh"),
	TutsuwaNima: ShrineDoubleSword("Tutsuwa Nima"),
	VooLota: Shrine("Voo Lota"),
	WahgoKatta: Shrine("Wahgo Katta"),
	YaNaga: Shrine("Ya Naga"),
	YahRin: Shrine("Yah Rin"),
	YowakaIta: ShrineDLC("Yowaka Ita"),
	ZaltaWa: Shrine("Zalta Wa"),
	ZeKasho: Shrine("Ze Kasho"),
	ZunaKai: ShrineBlessing("Zuna Kai"),
        
};

export const Koroks = {

	A01: Korok("A01", "Lift Rock (Tree)"),
	A02: Korok("A02", "Rock Circle"),
	A03: Korok("A03", "Lift Rock Blocked", "Under Boulder 1 STS"),
	A04: Korok("A04", "Flower Count"),
	A05: Korok("A05", "Race", "Cardinal High"),
	A06: Korok("A06", "Lift Rock Blocked", "Under slab 1 STS"),
	A07: Korok("A07", "Boulder Golf"),
	A08: Korok("A08", "Lift Rock Blocked", "Under rubble"),
	A09: Korok("A09", "Lift Rock Blocked", "Under slab 1 STS hit"),
	A10: Korok("A10", "Lift Rock Blocked", "Under slab 1 STS"),
	A11: Korok("A11", "Lift Rock (Tree)"),
	A12: Korok("A12", "Balloon", "Static under hanging cliff"),
	A13: Korok("A13", "Lift Rock Blocked", "Under Leaves"),
	A14: Korok("A14", "Race", cps(".E")),
	A15: Korok("A15", "Lift Rock"),
	A16: Korok("A16", "Confetti"),
	A17: Korok("A17", "Flower Count", "Start top of guardian"),
	A18: Korok("A18", "Acorn in Log", "Shoot midair"),
	A19: Korok("A19", "Flower Count"),
	A20: Korok("A20", "Block Puzzle"),
	A21: Korok("A21", "Lift Rock", "Side of spring"),
	A22: Korok("A22", "Lift Rock Blocked", "Under Leaves"),
	A23: Korok("A23", "Rock Circle"),
	A24: Korok("A24", "Block Puzzle"),
	A25: Korok("A25", "Confetti", "Top of tree"),
	A26: Korok("A26", "Block Puzzle"),
	A27: Korok("A27", "Light Chase"),
	A28: Korok("A28", "Race", "Ordinal DEFUSE"),
	A29: Korok("A29", "Balloon", "1 BA middle"),
	A30: Korok("A30", "Light Chase"),
	A31: Korok("A31", "Lift Rock Blocked", "Under leaves"),
	A32: Korok("A32", "Match Tree", "Closest tree"),
	A33: Korok("A33", "Lift Rock Blocked", "Under leaves"),
	A34: Korok("A34", "Rock Circle", "Rock in bush"),
	A35: Korok("A35", "Flower Chase"),
	A36: Korok("A36", "Block Puzzle"),
	A37: Korok("A37", "Lift Rock", "Top of stone structure"),
	A38: Korok("A38", "Flower Chase", "On bridge"),
	A39: Korok("A39", "Lift Rock (Door)"),
	A40: Korok("A40", "Lift Rock Blocked", "Under Leaves"),
	A41: Korok("A41", "Lift Rock Blocked", "Under Leaves"),
	A42: Korok("A42", "Lift Rock", "Next to cannons"),
	A43: Korok("A43", "Lift Rock Blocked", "Under Leaves"),
	A44: Korok("A44", "Race", gale()).extend({ability:{gale:1}}),
	A45: Korok("A45", "Rock Circle"),
	A46: Korok("A46", "Lift Rock (Door)"),
	A47: Korok("A47", "Offer Apple"),
	A48: Korok("A48", "Flower Chase"),
	A49: Korok("A49", "Match Tree", "Right tree"),
	A50: Korok("A50", "Lift Rock Blocked", "Broken column. STS MAX"),
	A51: Korok("A51", "Basketball", "GG rock throw"),
	A52: Korok("A52", "Lift Rock", "Below bridge"),
	A53: Korok("A53", "Match Tree", "Middle"),
	A54: Korok("A54", "Balloon", "Pre BT left of tree"),
	A55: Korok("A55", "Lift Rock Blocked", "Under Boulder"),
	A56: Korok("A56", "Light Chase"),
	A57: Korok("A57", "Confetti", "Top of tree"),
	C01: Korok("C01", "Lift Rock"),
	C02: Korok("C02", "Block Puzzle"),
	C03: Korok("C03", "Block Puzzle"),
	C04: Korok("C04", "Lift Rock", "In fountain"),
	C05: Korok("C05", "Acorn", "In tree"),
	C06: Korok("C06", "Lily Pads", "No Drown"),
	C07: Korok("C07", "Acorn Flying"),
	C08: Korok("C08", "Offer Shield", "Leave shield"),
	C09: Korok("C09", "Confetti", "Top of tree"),
	C10: Korok("C10", "Basketball", "2 Cryo blocks"),
	C11: Korok("C11", "Lift Rock", "Inside hollow tree"),
	C12: Korok("C12", "Lift Rock", "In tree stump on peak"),
	C13: Korok("C13", "Basketball", "Cryo block near rocks"),
	C14: Korok("C14", "Lift Rock"),
	C15: Korok("C15", "Lily Pads","Cryo block"),
	C16: Korok("C16", "Acorn"),
	C17: Korok("C17", "Lift Rock", "Under leaves"),
	C18: Korok("C18", "Light Chase"),
	C19: Korok("C19", "Balloon", "Pinwheel on hollow tree"),
	C20: Korok("C20", "Lift Rock Blocked", "Under rubble"),
	C21: Korok("C21", "Rock Circle"),
	C22: Korok("C22", "Rock Circle"),
	C23: Korok("C23", "Acorn", "Hanging below bridge"),
	C24: Korok("C24", "Lift Rock", "On small hill near bridge"),
	C25: Korok("C25", "Lift Rock"),
	C26: Korok("C26", "Balloon", "In tree"),
	C27: Korok("C27", "Race", "Aim at castle door turn"),
	C28: Korok("C28", "Lift Rock (Door)"),
	C29: Korok("C29", "Confetti", "Top of flagpole"),
	C30: Korok("C30", "Lift Rock Blocked", "Under rubble was smashed"),
	C31: Korok("C31", "Lift Rock", "On wall"),
	C32: Korok("C32", "Shoot Emblem", "Castle Town Gate"),
	C33: Korok("C33", "Balloon", "On out wall"),
	C34: Korok("C34", "Match Tree", "Left tree"),
	C35: Korok("C35", "Lift Rock", "On pillar"),
	C36: Korok("C36", "Lift Rock"),
	C37: Korok("C37", "Block Puzzle"),
	C38: Korok("C38", "Flower Chase"),
	C39: Korok("C39", "Confetti", "Top of flag pole"),
	C40: Korok("C40", "Light Chase", "Same Forest"),
	C41: Korok("C41", "Acorn", "In tree"),
	C42: Korok("C42", "Balloon", "Shoot midair"),
	C43: Korok("C43", "Acorn Flying"),
	C44: Korok("C44", "Lift Rock"),
	C45: Korok("C45", "Lift Rock", "On hill"),
	C46: Korok("C46", "Lift Rock", "Under bridge"),
	C47: Korok("C47", "Lily Pads", "Cryo"),
	C48: Korok("C48", "Lift Rock", "Between 2 rocks"),
	C49: Korok("C49", "Acorn", "Hanging from wagon (tree)"),
	C50: Korok("C50", "Flower Count", "Chaos Ranch"),
	C51: Korok("C51", "Boulder Circle"),
	C52: Korok("C52", "Lift Rock", "In well"),
	C53: Korok("C53", "Offer Apple"),
	C54: Korok("C54", "Confetti", "Top of flagpole"),
	C55: Korok("C55", "Light Chase", "Forest left of guardian"),
	C56: Korok("C56", "Offer Apple"),
	C57: Korok("C57", "Acorn", "In tree"),
	C58: Korok("C58", "Tree Stump"),
	C59: Korok("C59", "Basketball", "Cryo block"),
	C60: Korok("C60", "Block Puzzle"),
	C61: Korok("C61", "Rock Circle"),
	C62: Korok("C62", "Light Chase"),
	C63: Korok("C63", "Flower Chase"),
	C64: Korok("C64", "Light Chase"),
	C65: Korok("C65", "Acorn", "In tree"),
	C66: Korok("C66", "Rock Circle"),
	C67: Korok("C67", "Lift Rock", "On ledge (Hard to see)"),
	C68: Korok("C68", "Acorn", "Hanging on bridge"),
	C69: Korok("C69", "Acorn", "Hanging from tree"),
	C70: Korok("C70", "Rock Circle", "3"),
	C71: Korok("C71", "Lift Rock (Tree)"),
	C72: Korok("C72", "Acorn Flying", "BT"),
	C73: Korok("C73", "Race", "SQ High"),
	C74: Korok("C74", "Lift Rock", "Top of Coliseum"),
	C75: Korok("C75", "Lily Pads", "No Drown"),
	C76: Korok("C76", "Lift Rock Blocked", "Under leaves"),
	C77: Korok("C77", "Balloon"),
	C78: Korok("C78", "Lift Rock"),
	C79: Korok("C79", "Lift Rock"),
	C80: Korok("C80", "Acorn in Log", "Shoot midair"),
	C81: Korok("C81", "Light Chase", "In ruins"),
	C82: Korok("C82", "Light Chase"),
	C83: Korok("C83", "Balloon", "Rotate to the left"),
	C84: Korok("C84", "Acorn Flying", "Shoot hard one in non BT"),
	C85: Korok("C85", "Lift Rock (Tree)"),
	C86: Korok("C86", "Lift Rock"),
	C87: Korok("C87", "Basketball"),
	C88: Korok("C88", "Lily Pads", "Cryo Block"),
	C89: Korok("C89", "Basketball", "GG throw"),
	D01: Korok("D01", "Lift Rock", "Island below"),
	D02: Korok("D02", "Lily Pads", "Impa house. Cryo"),
	D03: Korok("D03", "Offer Apple"),
	D04: Korok("D04", "Lift Rock", "Ledge"),
	D05: Korok("D05", "Shoot Emblem"),
	D06: Korok("D06", "Shoot Emblem"),
	D07: Korok("D07", "Lift Rock", "2nd Peak"),
	D08: Korok("D08", "Lift Rock", "On ledge"),
	D09: Korok("D09", "Match Tree", "Closest to peak"),
	D10: Korok("D10", "Lift Rock", "2nd Peak"),
	D11: Korok("D11", "Lift Rock", "Peak"),
	D12: Korok("D12", "Block Puzzle"),
	D13: Korok("D13", "Lift Rock (Tree)", "3rd big tree N of open rock"),
	D14: Korok("D14", "Acorn", "Hanging from bridge"),
	D15: Korok("D15", "Tree Stump", "Edge of forest"),
	D16: Korok("D16", "Lift Rock", "Small island"),
	D17: Korok("D17", "Lift Rock (Tree)"),
	D18: Korok("D18", "Lily Pads", "No Drown"),
	D19: Korok("D19", "Basketball", "no GG"),
	D20: Korok("D20", "Basketball", "GG a rock down"),
	D21: Korok("D21", "Confetti", "Top of tree"),
	D22: Korok("D22", "Lift Rock Blocked", "Under boulder"),
	D23: Korok("D23", "Acorn Flying"),
	D24: Korok("D24", "Boulder Golf", "Surf down after bomb"),
	D25: Korok("D25", "Jump Fence", "Summon Horse"),
	D26: Korok("D26", "Confetti", "Top of flagpole"),
	D27: Korok("D27", "Lift Rock", "Under bridge"),
	D28: Korok("D28", "Confetti", "Top of flagpole"),
	D29: Korok("D29", "Lift Rock", "On island"),
	D30: Korok("D30", "Offer Apple"),
	D31: Korok("D31", "Boulder Golf"),
	D32: Korok("D32", "Basketball", "GG throw p close"),
	D33: Korok("D33", "Block Puzzle"),
	D34: Korok("D34", "Lift Rock"),
	D35: Korok("D35", "Balloon"),
	D36: Korok("D36", "Flower Chase"),
	D37: Korok("D37", "Boulder Golf"),
	D38: Korok("D38", "Lift Rock", "In cave"),
	D39: Korok("D39", "Flower Chase", "Across River"),
	D40: Korok("D40","Lift Rock"),
	D41: Korok("D41", "Boulder Golf"),
	D42: Korok("D42", "Confetti", "Top of stable"),
	D43: Korok("D43", "Flower Count", "In cave"),
	D44: Korok("D44", "Lift Rock"),
	D45: Korok("D45", "Confetti"),
	D46: Korok("D46", "Match Tree", "Right tree"),
	D47: Korok("D47", "Balloon"),
	D48: Korok("D48", "Lift Rock", "Upper level"),
	D49: Korok("D49", "Offer Apple"),
	D50: Korok("D50", "Lift Rock Blocked", "Under slab"),
	D51: Korok("D51", "Lift Rock (Tree)", "Big tree"),
	D52: Korok("D52", "Balloon"),
	D53: Korok("D53", "Lily Pads", "Put cryo"),
	D54: Korok("D54", "Torch"),
	D55: Korok("D55", "Lift Rock", "On ledge high"),
	D56: Korok("D56", "Lift Rock", "Tree stump"),
	D57: Korok("D57", "Lily Pads", "No Drown"),
	D58: Korok("D58", "Acorn Flying", "Bomb Arrow"),
	D59: Korok("D59", "Lift Rock", "Bottom of waterfall"),
	E01: Korok("E01", "Lift Rock Blocked", "Under leaves (Eye)"),
	E02: Korok("E02", "Block Puzzle"),
	E03: Korok("E03", "Lift Rock Blocked", "Under Rubble"),
	E04: Korok("E04", "Lift Rock Blocked", "Under Rubble"),
	E05: Korok("E05", "Rock Circle", "Pillars around shrine"),
	E06: Korok("E06", "Lift Rock Blocked", "Under rubble"),
	E07: Korok("E07", "Lift Rock", "Top of island"),
	E08: Korok("E08", "Lift Rock", "Top of northern mine"),
	E09: Korok("E09", "Lift Rock", "On hanging rock high"),
	E10: Korok("E10", "Balloon"),
	E11: Korok("E11", "Rock Circle"),
	E12: Korok("E12", "Block Puzzle"),
	E13: Korok("E13", "Lift Rock"),
	E14: Korok("E14", "Race", "SQ"),
	E15: Korok("E15", "Confetti", "Inside agreeGe"),
	E16: Korok("E16", "Confetti", "Top of skeleton"),
	E17: Korok("E17", "Race", "Glide over"),
	E18: Korok("E18", "Rock Circle", "GG over"),
	E19: Korok("E19", "Balloon","High up"),
	E20: Korok("E20", "Boulder Golf", "Can go after bomb"),
	E21: Korok("E21", "Block Puzzle"),
	E22: Korok("E22", "Lift Rock", "On stone above ring"),
	E23: Korok("E23", "Lift Rock Blocked", "Under rubble"),
	E24: Korok("E24", "Boulder Golf", "WB away after"),
	E25: Korok("E25", "Race", "Glide and run"),
	E26: Korok("E26", "Boulder Golf", "Bomb down"),
	E27: Korok("E27", "Lift Rock Blocked", "Under rubble"),
	E28: Korok("E28", "Balloon", "Aim Above"),
	E29: Korok("E29", "Basketball"),
	E30: Korok("E30", "Block Puzzle"),
	E31: Korok("E31", "Rock Circle", "2 rocks"),
	E32: Korok("E32", "Lift Rock Blocked", "Under rubble"),
	E33: Korok("E33", "Race", wb(cps)("N> Turn")),
	E34: Korok("E34", "Rock Circle"),
	E35: Korok("E35", "Rock Circle"),
	E36: Korok("E36", "Lily Pads", "No Drown"),
	E37: Korok("E37", "Rock Circle"),
	E38: Korok("E38", "Block Puzzle"),
	E39: Korok("E39", "Basketball", "GG throw"),
	E40: Korok("E40", "Lift Rock Blocked", "Under rubble"),
	E41: Korok("E41", "Balloon", "Shoot from E42"),
	E42: Korok("E42", "Lift Rock", "Ledge below stone thing"),
	E43: Korok("E43", "Lift Rock Blocked", "Cave behind rubble"),
	E44: Korok("E44", "Lift Rock", "Left set of trees"),
	E45: Korok("E45", "Race", "ordinal DEFUSE"),
	F01: Korok("F01", "Acorn", "In tree"),
	F02: Korok("F02", "Race", "<S Turn"),
	F03: Korok("F03", "Balloon"),
	F04: Korok("F04", "Rock Circle", "Use tree"),
	F05: Korok("F05", "Balloon"),
	F06: Korok("F06", "Lift Rock", "Peak"),
	F07: Korok("F07", "Light Chase"),
	F08: Korok("F08", "Lift Rock (Tree)"),
	F09: Korok("F09", "Basketball", "2 STS hits"),
	F10: Korok("F10", "Flower Chase", "In cave"),
	F11: Korok("F11", "Lift Rock", "Peak"),
	F12: Korok("F12", "Flower Chase"),
	F13: Korok("F13", "Lift Rock", "Under tree"),
	F14: Korok("F14", "Lily Pads", "No Drown"),
	F15: Korok("F15", "Light Chase"),
	F16: Korok("F16", "Race", gale()).extend({ability:{gale: 1}}),
	F17: Korok("F17", "Well", "(Mag boulder in stone)"),
	F18: Korok("F18", "Lift Rock Blocked", "Under rubble in cave"),
	F19: Korok("F19", "Race", "Swim up"),
	F20: Korok("F20", "Match Tree", "Closest"),
	F21: Korok("F21", "Offer Apple"),
	F22: Korok("F22", "Flower Chase", "Round trip"),
	F23: Korok("F23", "Flower Chase"),
	F24: Korok("F24", "Balloon", "Shoot from bridge"),
	F25: Korok("F25", "Offer Durian"),
	F26: Korok("F26", "Block Puzzle", "Middle of waterfall"),
	F27: Korok("F27", "Lift Rock", "Ledge"),
	F28: Korok("F28", "Flower Chase", gale()).extend({ability:{gale: 1}}),
	F29: Korok("F29", "Block Puzzle", "Piece in lake, cryo"),
	F30: Korok("F30", "Match Tree", "West tree"),
	F31: Korok("F31", "Lift Rock Blocked", "Under leaves"),
	F32: Korok("F32", "Light Chase"),
	F33: Korok("F33", "Lift Rock", "On ledge"),
	F34: Korok("F34", "Balloon", "3"),
	F35: Korok("F35", "Luminous Stone", "Eye of statue"),
	F36: Korok("F36", "Rock Circle", "STS tree"),
	F37: Korok("F37", "Lily Pads", "No Drown"),
	F38: Korok("F38", "Lift Rock"),
	F39: Korok("F39", "Offer Durian"),
	F40: Korok("F40", "Lift Rock", "middle of mud"),
	F41: Korok("F41", "Bomb Beard"),
	F42: Korok("F42", "Balloon", "Middle of bridge"),
	F43: Korok("F43", "Rock Circle"),
	F44: Korok("F44", "Apple", "Bomb top of palm tree"),
	F45: Korok("F45", "Flower Chase", "Top of house"),
	F46: Korok("F46", "Block Puzzle"),
	F47: Korok("F47", "Lift Rock", "Peak"),
	F48: Korok("F48", "Offer Banana", "banana next to it"),
	F49: Korok("F49", "Rock Circle"),
	F50: Korok("F50", "Flower Chase", "Turn around after beach"),
	F51: Korok("F51", "Lily Pads"),
	F52: Korok("F52", "Lift Rock"),
	F53: Korok("F53", "Rock Circle"),
	F54: Korok("F54", "Lift Rock", "Ledge beach level"),
	F55: Korok("F55", "Lift Rock", "Upper ledge"),
	F56: Korok("F56", "Balloon", "Under cliff"),
	F57: Korok("F57", "Rock Circle", "Heart"),
	F58: Korok("F58", "Lily Pads", "Close to beach rocks"),
	G01: Korok("G01", "Boulder Golf", "Bomb down STS hit in"),
	G02: Korok("G02", "Race", "Run"),
	G03: Korok("G03", "Rock Circle"),
	G04: Korok("G04", "Block Puzzle"),
	G05: Korok("G05", "Race", cps("S>")),
	G06: Korok("G06", "Lift Rock", "On wood platform"),
	G07: Korok("G07", "Ice Block", "2 Fire Arrows"),
	G08: Korok("G08", "Flower Chase", gale()).extend({ability:{gale:1}}),
	G09: Korok("G09", "Rock Circle"),
	G10: Korok("G10", "Rock Circle"),
	G11: Korok("G11", "Race", wb(cps)("<E")),
	G12: Korok("G12", "Block Puzzle"),
	G13: Korok("G13", "Confetti", "Top of tree"),
	G14: Korok("G14", "Balloon"),
	G15: Korok("G15", "Lift Rock"),
	G16: Korok("G16", "Light Chase",),
	G17: Korok("G17", "Ice Block"),
	G18: Korok("G18", "Ice Block", "Far one"),
	G19: Korok("G19", "Rock Circle"),
	G20: Korok("G20", "Rock Circle"),
	G21: Korok("G21", "Block Puzzle"),
	G22: Korok("G22", "Rock Circle"),
	G23: Korok("G23", "Lift Rock", "Peak far"),
	G24: Korok("G24", "Rock Circle"),
	G25: Korok("G25", "Offer Banana", "Pick up 3"),
	G26: Korok("G26", "Snowball Golf", "Carry halfway"),
	G27: Korok("G27", "Rock Circle", "Platform on cliff"),
	G28: Korok("G28", "Block Puzzle"),
	G29: Korok("G29", "Block Puzzle"),
	G30: Korok("G30", "Rock Circle"),
	G31: Korok("G31", "Balloon", "Wait in BT"),
	G32: Korok("G32", "Race", "Run"),
	G33: Korok("G33", "Rock Circle"),
	G34: Korok("G34", "Block Puzzle", "Bottom right"),
	G35: Korok("G35", "Race", "SQ DEFUSE"),
	G36: Korok("G36", "Well"),
	H01: Korok("H01", "Block Puzzle"),
	H02: Korok("H02", "Ice Block", "Left one"),
	H03: Korok("H03", "Flower Chase"),
	H04: Korok("H04", "Rock Circle", "Rock behind camp"),
	H05: Korok("H05", "Balloon", "Bomb Arrow (Turn around)"),
	H06: Korok("H06", "Rock Circle"),
	H07: Korok("H07", "Race", "Surf down FAST"),
	H08: Korok("H08", "Balloon", "SBR"),
	H09: Korok("H09", "Lift Rock Blocked", "Under leaves"),
	H10: Korok("H10", "Acorn in Log", "Farthest set of trees"),
	H11: Korok("H11", "Confetti", "Top of bare tree"),
	H12: Korok("H12", "Rock Circle"),
	H13: Korok("H13", "Ice Block", "3 FA"),
	H14: Korok("H14", "Acorn in Log"),
	H15: Korok("H15", "Block Puzzle"),
	H16: Korok("H16", "Balloon", "Bomb tree"),
	H17: Korok("H17", "Rock Circle", "Snowy Platform"),
	H18: Korok("H18", "Confetti", "Forest with 5 trees"),
	H19: Korok("H19", "Balloon", "First Forest on right"),
	H20: Korok("H20", "Confetti", "Top of house"),
	H21: Korok("H21", "Confetti", "Top of tree"),
	H22: Korok("H22", "Boulder Golf", "WB away after"),
	H23: Korok("H23", "Lift Rock", "Peak far"),
	H24: Korok("H24", "Flower Chase", "Below high forest"),
	H25: Korok("H25", "Lift Rock", "In corner"),
	H26: Korok("H26", "Lift Rock"),
	H27: Korok("H27", "Balloon"),
	H28: Korok("H28", "Lift Rock"),
	H29: Korok("H29", "Ice Block", "3-4 FA"),
	H30: Korok("H30", "Acorn Flying"),
	H31: Korok("H31", "Ice Block", "2 FA"),
	H32: Korok("H32", "Light Chase", "On flat hill"),
	H33: Korok("H33", "Ice Block"),
	H34: Korok("H34", "Ice Block"),
	H35: Korok("H35", "Lift Rock", "Clear Ragdoll"),
	H36: Korok("H36", "Rock Circle", "2"),
	H37: Korok("H37", "Light Chase"),
	H38: Korok("H38", "Lift Rock Blocked", "Under rubble"),
	H39: Korok("H39", "Flower Chase", "A bit over updraft"),
	H40: Korok("H40", "Lift Rock", "Top of hill"),
	H41: Korok("H41", "Rock Circle"),
	H42: Korok("H42", "Lift Rock Blocked", "Drop down 2 levels"),
	H43: Korok("H43", "Acorn in Log"),
	H44: Korok("H44", "Balloon", "In cave"),
	H45: Korok("H45", "Ice Block"),
	H46: Korok("H46", "Ice Block"),
	H47: Korok("H47", "Balloon", "End of river BA"),
	H48: Korok("H48", "Lift Rock", "On ledge"),
	H49: Korok("H49", "Race", "Run finish race"),
	H50: Korok("H50", "Balloon", "Middle of river"),
	H51: Korok("H51", "Lift Rock", "Ledge down the camp"),
	H52: Korok("H52", "Acorn in Log"),
	H53: Korok("H53", "Lift Rock", "Sharp hill"),
	H54: Korok("H54", "Lift Rock"),
	H55: Korok("H55", "Balloon"),
	H56: Korok("H56", "Flower Chase", "Across bridge"),
	H57: Korok("H57", "Snowball Golf"),
	H58: Korok("H58", "Lift Rock Blocked", "Under leaves"),
	H59: Korok("H59", "Boulder Golf"),
	H60: Korok("H60", "Balloon"),
	H61: Korok("H61", "Lift Rock", "Peak"),
	H62: Korok("H62", "Balloon", "1 below 2 behind"),
	H63: Korok("H63", "Lift Rock", "Ledge"),
	H64: Korok("H64", "Lift Rock", "Behind shrine"),
	H65: Korok("H65", "Confetti", "Top of tree (island)"),
	H66: Korok("H66", "Lily Pads", "No Drown"),
	H67: Korok("H67", "Well"),
	H68: Korok("H68", "Lift Rock"),
	H69: Korok("H69", "Acorn in Log", "Midair"),
	H70: Korok("H70", "Flower Chase"),
	H71: Korok("H71", "Lift Rock Blocked", "Under rubble"),
	H72: Korok("H72", "Confetti", "Top of windmill"),
	H73: Korok("H73", "Race", cps("<N")),
	K01: Korok("K01", "Lift Rock", "On peak FAR"),
	K02: Korok("K02", "Block Puzzle"),
	K03: Korok("K03", "Rock Circle"),
	K04: Korok("K04", "Balloon", "5 around tree"),
	K05: Korok("K05", "Balloon", "Backflip BT"),
	K06: Korok("K06", "Acorn in Log", "Shoot from midair"),
	K07: Korok("K07", "Balloon", "No BT"),
	K08: Korok("K08", "Balloon", "Instant Shoot"),
	K09: Korok("K09", "Lift Rock", "Behind statue"),
	K10: Korok("K10", "Block Puzzle", "Cube behind left group"),
	K11: Korok("K11", "Lift Rock", "Peak FAR"),
	K12: Korok("K12", "Lift Rock Blocked", "Under rubble"),
	K13: Korok("K13", "Lift Rock Blocked", "Under rubble"),
	K14: Korok("K14", "Lift Rock (Door)"),
	K15: Korok("K15", "Lift Rock", "On pillar"),
	K16: Korok("K16", "Acorn in Log"),
	K17: Korok("K17", "Jump Fence", "Summon Horse"),
	K18: Korok("K18", "Confetti", "Top of broken hut"),
	K19: Korok("K19", "Acorn in Log"),
	K20: Korok("K20", "Lift Rock", "End of ledge"),
	K21: Korok("K21", "Lift Rock Blocked", "Under rubble"),
	K22: Korok("K22", "Lift Rock Blocked","In corner under rubble"),
	K23: Korok("K23", "Acorn in Log", "Shoot midair"),
	K24: Korok("K24", "Light Chase"),
	K25: Korok("K25", "Rock Circle"),
	K26: Korok("K26", "Balloon", "Pinwheel"),
	K27: Korok("K27", "Balloon"),
	K28: Korok("K28", "Lift Rock"),
	K29: Korok("K29", "Acorn in Log"),
	K30: Korok("K30", "Lift Rock", "Ledge"),
	K31: Korok("K31", "Lift Rock", "Top of scaffolding"),
	K32: Korok("K32", "Acorn", "In tree"),
	K33: Korok("K33", "Block Puzzle"),
	K34: Korok("K34", "Lily Pads", "No Drown"),
	K35: Korok("K35", "Block Puzzle"),
	L01: Korok("L01", "Well"),
	L02: Korok("L02", "Lift Rock", "In big tree stump"),
	L03: Korok("L03", "Block Puzzle",),
	L04: Korok("L04", "Tree Stump"),
	L05: Korok("L05", "Flower Chase"),
	L06: Korok("L06", "Light Chase"),
	L07: Korok("L07", "Boulder Golf", "5 STS hits aim straight"),
	L08: Korok("L08", "Race", "SQ DEFUSE"),
	L09: Korok("L09", "Basketball"),
	L10: Korok("L10", "Lily Pads", "No Drown"),
	L11: Korok("L11", "Tree Stump"),
	L12: Korok("L12", "Block Puzzle", "Piece on tree"),
	L13: Korok("L13", "Lift Rock Blocked", "Under rubble"),
	L14: Korok("L14", "Lift Rock Blocked", "Under slab (STS a lot)"),
	L15: Korok("L15", "Balloon", "In pillar"),
	L16: Korok("L16", "Boulder Golf", "Bomb down stasis"),
	L17: Korok("L17", "Light Chase"),
	L18: Korok("L18", "Light Chase"),
	L19: Korok("L19", "Lift Rock (Tree)", "Top of big tree"),
	L20: Korok("L20", "Block Puzzle"),
	L21: Korok("L21", "Block Puzzle"),
	L22: Korok("L22", "Acorn", "Hanging from tree"),
	L23: Korok("L23", "Confetti", "Top of tree"),
	L24: Korok("L24", "Lift Rock", "3rd hole"),
	L25: Korok("L25", "Confetti", "Top of tree"),
	L26: Korok("L26", "Tree Branch"),
	L27: Korok("L27", "Confetti", "Top of fountain"),
	L28: Korok("L28", "Flower Count", "On peak"),
	L29: Korok("L29", "Lift Rock", "Peak"),
	L30: Korok("L30", "Flower Chase"),
	L31: Korok("L31", "Lift Rock"),
	L32: Korok("L32", "Metal Box Circle"),
	L33: Korok("L33", "Balloon"),
	L34: Korok("L34", "Boulder Circle", "STS Jump ATK down"),
	L35: Korok("L35", "Match Tree",txt("Right, ", "2 durians")),
	L36: Korok("L36", "Balloon", "Bomb in tree"),
	L37: Korok("L37", "Acorn in Log"),
	L38: Korok("L38", "Block Puzzle", "2nd hole"),
	L39: Korok("L39", "Lift Rock"),
	L40: Korok("L40", "Acorn", "In tree"),
	L41: Korok("L41", "Lift Rock Blocked", "Under rubble"),
	L42: Korok("L42", "Boulder Golf", "Bomb in"),
	L43: Korok("L43", "Light Chase"),
	L44: Korok("L44", "Boulder Golf"),
	L45: Korok("L45", "Lift Rock"),
	L46: Korok("L46", "Lift Rock", "Top of small waterfall"),
	L47: Korok("L47", "Race"),
	L48: Korok("L48", "Lift Rock"),
	L49: Korok("L49", "Rock Circle"),
	L50: Korok("L50", "Block Puzzle"),
	L51: Korok("L51", "Boulder Golf", "2 STS + bomb in"),
	L52: Korok("L52", "Lift Rock", "On pillar"),
	L53: Korok("L53", "Tree Stump", "Left next to shrine"),
	L54: Korok("L54", "Lily Pads", "No Drown"),
	L55: Korok("L55", "Flower Chase"),
	L56: Korok("L56", "Boulder Circle", rne("STS + Magnesis")),
	L57: Korok("L57", "Light Chase"),
	L58: Korok("L58", "Light Chase"),
	L59: Korok("L59", "Lily Pads", "No Drown"),
	L60: Korok("L60", "Lift Rock Blocked", "Under rubble"),
	L61: Korok("L61", "Lift Rock Blocked", "Under slab (1 STS hit)"),
	L62: Korok("L62", "Lift Rock", "Under rubble (mid of 3)"),
	L63: Korok("L63", "Offer Apple"),
	L64: Korok("L64", "Flower Chase"),
	L65: Korok("L65", "Race", "Ordinal"),
	L66: Korok("L66", "Basketball", "Cryo block"),
	L67: Korok("L67", "Balloon", "SBR"),
	L68: Korok("L68", "Light Chase"),
	L69: Korok("L69", "Block Puzzle"),
	L70: Korok("L70", "Acorn Flying", "Bomb Arrow if can"),
	L71: Korok("L71", "Rock Circle"),
	L72: Korok("L72", "Race", wb(cps)("N> Turn")),
	L73: Korok("L73", "Balloon", "On peak"),
	L74: Korok("L74", "Boulder Golf", "Drop down STS"),
	L75: Korok("L75", "Lily Pads", "No Drown"),
	L76: Korok("L76", "Boulder Golf", "Stasis 2 + BTMA"),
	L77: Korok("L77", "Rock Circle"),
	L78: Korok("L78", "Lift Rock", "Peak"),
	L79: Korok("L79", "Rock Circle"),
	L80: Korok("L80", "Race", "cardinal"),
	L81: Korok("L81", "Lift Rock"),
	L82: Korok("L82", "Confetti", "Top of palm tree"),
	L83: Korok("L83", "Lift Rock Blocked", "Under Rubble"),
	L84: Korok("L84", "Light Chase"),
	L85: Korok("L85", "Rock Circle"),
	L86: Korok("L86", "Lift Rock Blocked", "Under Boulder"),
	L87: Korok("L87", "Lift Rock", "Top of rock"),
	L88: Korok("L88", "Light Chase"),
	L89: Korok("L89", "Lily Pads", "SEAWEED"),
	L90: Korok("L90", "Block Puzzle"),
	L91: Korok("L91", "Rock Circle"),
	L92: Korok("L92", "Block Puzzle"),
	N01: Korok("N01", "Lift Rock (Tree)"),
	N02: Korok("N02", "Lift Rock (Tree)"),
	N03: Korok("N03", "Lift Rock (Tree)", "behind shrine"),
	N04: Korok("N04", "Acorn Flying", "Bullet time"),
	N05: Korok("N05", "Light Chase", "Small pond"),
	N06: Korok("N06", "Confetti", "Top of tall tree"),
	N07: Korok("N07", "Match Tree", "Bomb left"),
	N08: Korok("N08", "Block Puzzle"),
	N09: Korok("N09", "Offer Apple"),
	N10: Korok("N10", "Flower Chase"),
	N11: Korok("N11", "Boulder Golf", "WB away after"),
	N12: Korok("N12", "Rock Circle"),
	N13: Korok("N13", "Boulder Circle", "2 separate STS hits"),
	N14: Korok("N14", "Rock Circle"),
	N15: Korok("N15", "Lily Pads"),
	N16: Korok("N16", "Lift Rock"),
	N17: Korok("N17", "Race", txt(cps("S"), " Round First DEFUSE")),
	N18: Korok("N18", "Ice Block", "3 Fire Arrows"),
	N19: Korok("N19", "Rock Circle"),
	N20: Korok("N20", "Rock Circle"),
	N21: Korok("N21", "Lift Rock", "Peak (FAR)"),
	N22: Korok("N22", "Block Puzzle"),
	N23: Korok("N23", "Light Chase", "In forest"),
	N24: Korok("N24", "Ice Block", "Behind peak 4 Fire Arrows"),
	N25: Korok("N25", "Boulder Golf", "Bomb + STS"),
	N26: Korok("N26", "Boulder Golf", "WB away after"),
	N27: Korok("N27", "Lift Rock Blocked", "Under rubble"),
	N28: Korok("N28", "Offer Apple"),
	N29: Korok("N29", "Lily Pads", "No Drown"),
	N30: Korok("N30", "Match Tree", "Farthest tree from lake"),
	N31: Korok("N31", "Ice Block", "3 Fire Arrows"),
	N32: Korok("N32", "Race", "SQ"),
	N33: Korok("N33", "Lift Rock (Door)"),
	N34: Korok("N34", "Acorn Flying"),
	N35: Korok("N35", "Block Puzzle"),
	N36: Korok("N36", "Acorn", "In tree"),
	N37: Korok("N37", "Lily Pads", "C ryo block DIVE"),
	N38: Korok("N38", "Balloon"),
	N39: Korok("N39", "Race", txt(cps("W"), " Round First")),
	N40: Korok("N40", "Lift Rock Blocked", "Under slab"),
	N41: Korok("N41", "Lily Pads", "Cryo block"),
	N42: Korok("N42", "Lift Rock (Tree)", "Next to blue flame"),
	N43: Korok("N43", "Lift Rock (Tree)", "middle of lake"),
	N44: Korok("N44", "Flower Chase"),
	N45: Korok("N45", "Balloon"),
	N46: Korok("N46", "Lift Rock (Door)"),
	N47: Korok("N47", "Confetti", "Top of lab"),
	N48: Korok("N48", "Lily Pads", "Drown"),
	N49: Korok("N49", "Acorn", "In tree. Shoot from N50"),
	N50: Korok("N50", "Match Tree", "Get Wood"),
	N51: Korok("N51", "Lift Rock", "Side of lake"),
	N52: Korok("N52", "Acorn", "In tree"),
	N53: Korok("N53", "Lift Rock"),
	N54: Korok("N54", "Offer Palm Fruit", "In cave"),
	N55: Korok("N55", "Balloon", "Turn Right"),
	N56: Korok("N56", "Lily Pads", "Cryo block wb"),
	N57: Korok("N57", "Flower Chase"),
	N58: Korok("N58", "Block Puzzle"),
	N59: Korok("N59", "Flower Chase", "6 before going right"),
	N60: Korok("N60", "Basketball", "Cryo GG Throw"),
	N61: Korok("N61", "Rock Circle"),
	N62: Korok("N62", "Flower Chase", "Start on beach"),
	N63: Korok("N63", "Rock Circle", "3"),
	N64: Korok("N64", "Match Tree", txt("Right tree", rne("STS"), " BA")),
	N65: Korok("N65", "Rock Circle"),
	N66: Korok("N66", "Race"),
	P01: Korok("P01", "Lift Rock", "Under rocks"),
	P02: Korok("P02", "Tree Stump"),
	P03: Korok("P03", "Block Puzzle"),
	P04: Korok("P04", "Flower Chase", "Middle of log"),
	P05: Korok("P05", "Lift Rock Blocked", "Under leaves"),
	P06: Korok("P06", "Lift Rock", "Top of hill"),
	P07: Korok("P07", "Ice Block"),
	P08: Korok("P08", "Confetti", "Cryo log"),
	P09: Korok("P09", "Confetti", "Inside SOR"),
	P10: Korok("P10", "Lily Pads", "No Drown"),
	P11: Korok("P11", "Confetti", "Top of ToT"),
	P12: Korok("P12", "Lift Rock (Door)"),
	P13: Korok("P13", "Lift Rock (Door)"),
	P14: Korok("P14", "Block Puzzle"),
	P15: Korok("P15", "Rock Circle"),
	P16: Korok("P16", "Lift Rock Blocked", "Slab 1 STS hit"),
	P17: Korok("P17", "Lift Rock"),
	P18: Korok("P18", "Confetti", "Top of hut"),
	R01: Korok("R01", "Block Puzzle"),
	R02: Korok("R02", "Lift Rock"),
	R03: Korok("R03", "Lift Rock Blocked", "Under rubble"),
	R04: Korok("R04", "Rock Circle", "In Canyon"),
	R05: Korok("R05", "Acorn", "In tree"),
	R06: Korok("R06", "Confetti", "Top of bare tree"),
	R07: Korok("R07", "Lift Rock (Tree)"),
	R08: Korok("R08", "Lift Rock Blocked", "Under rubble"),
	R09: Korok("R09", "Race", "Run"),
	R10: Korok("R10", "Flower Chase"),
	R11: Korok("R11", "Basketball"),
	R12: Korok("R12", "Confetti", "Top of flagpole"),
	R13: Korok("R13", "Lift Rock", "Top of waterfall"),
	R14: Korok("R14", "Light Chase"),
	R15: Korok("R15", "Rock Circle", "3 on mushroom tree"),
	R16: Korok("R16", "Block Puzzle"),
	R17: Korok("R17", "Lift Rock", "Top of mountain"),
	R18: Korok("R18", "Race", "Run"),
	R19: Korok("R19", "Boulder Golf", "WB away after"),
	R20: Korok("R20", "Block Puzzle"),
	R21: Korok("R21", "Light Chase"),
	R22: Korok("R22", "Balloon", "Aim a bit above"),
	R23: Korok("R23", "Flower Chase"),
	R24: Korok("R24", "Lily Pads", "No Drown"),
	R25: Korok("R25", "Race", "Ordinal Delay"),
	R26: Korok("R26", "Race", cps("W")),
	R27: Korok("R27", "Acorn", "Hanging from bridge"),
	R28: Korok("R28", "Lift Rock Blocked", "Under slab"),
	R29: Korok("R29", "Lift Rock", "In between rocks"),
	R30: Korok("R30", "Race", "SQ"),
	R31: Korok("R31", "Balloon", "Aim direct"),
	R32: Korok("R32", "Balloon", "SBR"),
	R33: Korok("R33", "Rock Circle"),
	R34: Korok("R34", "Acorn", "Shoot from race"),
	R35: Korok("R35", "Race", "SQ DEFUSE"),
	R36: Korok("R36", "Lift Rock", "On ledge"),
	R37: Korok("R37", "Lift Rock", "Ledge"),
	R38: Korok("R38", "Match Tree", "Right tree"),
	R39: Korok("R39", "Light Chase", "Near 2 rocks"),
	R40: Korok("R40", "Lift Rock Blocked", "Under slab"),
	R41: Korok("R41", "Flower Count"),
	R42: Korok("R42", "Lift Rock", "Riverbank"),
	R43: Korok("R43", "Balloon", "Aim a bit above"),
	R44: Korok("R44", "Basketball", "GG rock throw"),
	R45: Korok("R45", "Flower Chase", "Start at pillar"),
	R46: Korok("R46", "Flower Count"),
	R47: Korok("R47", "Balloon"),
	R48: Korok("R48", "Acorn", "In tree"),
	R49: Korok("R49", "Block Puzzle"),
	R50: Korok("R50", "Balloon", "In tree"),
	R51: Korok("R51", "Rock Circle"),
	R52: Korok("R52", "Lift Rock (Tree)"),
	R53: Korok("R53", "Lift Rock Blocked", "Under rubble"),
	R54: Korok("R54", "Confetti", "Top of tree"),
	R55: Korok("R55", "Lift Rock", "In tree stump"),
	R56: Korok("R56", "Acorn", "In tree"),
	R57: Korok("R57", "Acorn", "In tree"),
	R58: Korok("R58", "Lift Rock (Tree)"),
	R59: Korok("R59", "Lift Rock", "Small island"),
	R60: Korok("R60", "Lift Rock Blocked", "Under leaves"),
	R61: Korok("R61", "Flower Chase"),
	R62: Korok("R62", "Race", "Cardinal"),
	R63: Korok("R63", "Lift Rock Blocked", "Under leaves"),
	R64: Korok("R64", "Lift Rock Blocked", "Under rubble"),
	R65: Korok("R65", "Flower Count"),
	R66: Korok("R66", "Tree Stump", "Magnesis 2"),
	R67: Korok("R67", "Basketball"),
	R68: Korok("R68", "Balloon", "Backflip"),
	R69: Korok("R69", "Acorn in Log", "Shoot from far"),
	R70: Korok("R70", "Lift Rock Blocked", "Under Boulder"),
	R71: Korok("R71", "Lift Rock"),
	R72: Korok("R72", "Lift Rock Blocked", "Under leaves"),
	R73: Korok("R73", "Boulder Golf", "Stasis + shoot"),
	R74: Korok("R74", "Lift Rock"),
	R75: Korok("R75", "Acorn", "Shoot midair"),
	R76: Korok("R76", "Lift Rock (Tree)"),
	R77: Korok("R77", "Acorn", "Hanging from tree"),
	R78: Korok("R78", "Offer Apple"),
	R79: Korok("R79", "Offer Apple"),
	R80: Korok("R80", "Lift Rock"),
	T01: Korok("T01", "Flower Chase", "Left to rubble"),
	T02: Korok("T02", "Confetti", "Top of house"),
	T03: Korok("T03", "Lily Pads", "No Drown"),
	T04: Korok("T04", "Well"),
	T05: Korok("T05", "Lift Rock"),
	T06: Korok("T06", "Race", txt(cps("NE"))),
	T07: Korok("T07", "Rock Circle", "3"),
	T08: Korok("T08", "Lift Rock"),
	T09: Korok("T09", "Offer Pepper"),
	T10: Korok("T10", "Offer Apple"),
	T11: Korok("T11", "Lift Rock (Tree)", "Big tree"),
	T12: Korok("T12", "Lift Rock Blocked", "Under leaves"),
	T13: Korok("T13", "Rock Circle"),
	T14: Korok("T14", "Balloon"),
	T15: Korok("T15", "Lift Rock"),
	T16: Korok("T16", "Flower Chase"),
	T17: Korok("T17", "Race", "Ordinal Low"),
	T18: Korok("T18", "Confetti", "Top of tree"),
	T19: Korok("T19", "Lily Pads", "No Drown"),
	T20: Korok("T20", "Block Puzzle"),
	T21: Korok("T21", "Lift Rock Blocked", "Under rubble"),
	T22: Korok("T22", "Lift Rock Blocked", "Under rubble"),
	T23: Korok("T23", "Rock Circle"),
	T24: Korok("T24", "Lift Rock", "Behind malice"),
	T25: Korok("T25", "Lift Rock", "On ledge"),
	T26: Korok("T26", "Tree Stump"),
	T27: Korok("T27", "Offer Apple"),
	T28: Korok("T28", "Boulder Golf", "Run after bomb"),
	T29: Korok("T29", "Lift Rock"),
	T30: Korok("T30", "Race", "SQ High"),
	T31: Korok("T31", "Offer Apple"),
	T32: Korok("T32", "Lift Rock", "On pillar"),
	T33: Korok("T33", "Balloon", "Use bomb"),
	T34: Korok("T34", "Race", wb(cps)("W")),
	T35: Korok("T35", "Lily Pads", "No Drown"),
	T36: Korok("T36", "Flower Count"),
	T37: Korok("T37", "Race", "SQ DEFUSE"),
	W01: Korok("W01", "Lift Rock"),
	W02: Korok("W02", "Offer Banana", "Pick up 4"),
	W03: Korok("W03", "Offer Banana", "No pick up, 1 left"),
	W04: Korok("W04", "Offer Banana", "Pick up all"),
	W05: Korok("W05", "Offer Banana", "Pick up 1"),
	W06: Korok("W06", "Flower Chase"),
	W07: Korok("W07", "Block Puzzle"),
	W08: Korok("W08", "Confetti", "In crack"),
	W09: Korok("W09", "Confetti", "Highest fin on skeleton"),
	W10: Korok("W10", "Balloon", "Bomb crack"),
	W11: Korok("W11", "Lift Rock (Tree)"),
	W12: Korok("W12", "Acorn", "Bomb midair"),
	W13: Korok("W13", "Confetti", "Highest fin on skeleton"),
	W14: Korok("W14", "Lift Rock", "End of bridge"),
	W15: Korok("W15", "Lift Rock", "On pillar"),
	W16: Korok("W16", "Boulder Golf", "2 MS Hits"),
	W17: Korok("W17", "Block Puzzle"),
	W18: Korok("W18", "Confetti", "Top of skeleton (pinwheel)"),
	W19: Korok("W19", "Lift Rock"),
	W20: Korok("W20", "Confetti", "In tree"),
	W21: Korok("W21", "Block Puzzle"),
	W22: Korok("W22", "Balloon"),
	W23: Korok("W23", "Race", "Drop down finish race"),
	W24: Korok("W24", "Lift Rock", "On platform"),
	W25: Korok("W25", "Match Cactus", "Shoot from statue"),
	W26: Korok("W26", "Block Puzzle"),
	W27: Korok("W27", "Balloon", "2 Bomb Arrows (No BT)"),
	W28: Korok("W28", "Race", "On some pillars"),
	W29: Korok("W29", "Race", "SQ DEFUSE"),
	W30: Korok("W30", "Block Puzzle"),
	W31: Korok("W31", "Lift Rock"),
	W32: Korok("W32", "Block Puzzle"),
	W33: Korok("W33", "Balloon", "Under bridge"),
	W34: Korok("W34", "Rock Circle"),
	W35: Korok("W35", "Balloon", "Between arms. Shoot midair"),
	W36: Korok("W36", "Match Cactus", "Shoot midair"),
	W37: Korok("W37", "Flower Chase", "On skeleton"),
	W38: Korok("W38", "Lift Rock", "On pillar"),
	W39: Korok("W39", "Block Puzzle"),
	W40: Korok("W40", "Lift Rock", "Top of statue"),
	W41: Korok("W41", "Lift Rock", "On overpass"),
	W42: Korok("W42", "Confetti"),
	W43: Korok("W43", "Flower Chase"),
	W44: Korok("W44", "Block Puzzle"),
	W45: Korok("W45", "Rock Circle"),
	W46: Korok("W46", "Lift Rock Blkd", "Corner"),
	W47: Korok("W47", "Flower Chase", "Right side of skeleton"),
	W48: Korok("W48", "Block Puzzle"),
	W49: Korok("W49", "Block Puzzle"),
	W50: Korok("W50", "Lift Rock", "Top of big pillar"),
	W51: Korok("W51", "Match Cactus", "Stasis left"),
	W52: Korok("W52", "Block Puzzle", "Inside skull"),
	W53: Korok("W53", "Lift Rock", "On pillar"),
	W54: Korok("W54", "Lift Rock"),
	W55: Korok("W55", "Lift Rock", "On a rock"),
	W56: Korok("W56", "Lift Rock"),
	W57: Korok("W57", "Balloon", "On tree in oasis"),
	W58: Korok("W58", "Race", wb(cps)("S Turn")),
	W59: Korok("W59", "Ice Block", "3 Fire Arrows"),
	W60: Korok("W60", "Ice Block", "3 Fire Arrows"),
	W61: Korok("W61", "Match Cactus", "STS (One hand weapon)"),
	W62: Korok("W62", "Rock Circle"),
	W63: Korok("W63", "Race"),
	W64: Korok("W64", "Rock Circle"),
	W65: Korok("W65", "Confetti", "Top of skeleton"),
	W66: Korok("W66", "Lift Rock"),
	W67: Korok("W67", "Match Cactus", "Shoot midair"),
	W68: Korok("W68", "Lift Rock", "On pillar"),
	X01: Korok("X01", "Lift Rock", "On ledge"),
	X02: Korok("X02", "Lily Pads", "No Drown"),
	X03: Korok("X03", "Lift Rock Blocked", "Under rubble"),
	X04: Korok("X04", "Balloon", "BA BT"),
	X05: Korok("X05", "Confetti", "Top of Castle"),
	X06: Korok("X06", "Balloon"),
	X07: Korok("X07", "Confetti", "Top of Zelda's Study"),
	X08: Korok("X08", "Lift Rock", "Wooden Platform"),
	X09: Korok("X09", "Lift Rock"),
	X10: Korok("X10", "Race", "Glide"),
	X11: Korok("X11", "Ice Block"),
	X12: Korok("X12", "Lift Rock"),
	X13: Korok("X13", "Offer Egg"),
	X14: Korok("X14", "Lift Rock Blocked", "Under rubble"),
	X15: Korok("X15", "Acorn", "Inside Room"),
	X16: Korok("X16", "Confetti", "Top of Second Gatehouse"),
	X17: Korok("X17", "Confetti", "Top of First Gatehouse"),
	X18: Korok("X18", "Lift Rock", "On wall"),
	X19: Korok("X19", "Acorn", "Inside 3AA Room"),
	X20: Korok("X20", "Lift Rock Blocked", "Under rubble"),
	X21: Korok("X21", "Shoot Emblem"),
	X22: Korok("X22", "Balloon", "Aim top wall in background"),
	X23: Korok("X23", "Balloon"),
	X24: Korok("X24", "Lift Rock", "On gate"),
	X25: Korok("X25", "Flower Chase", "Across bridge"),
	Z01: Korok("Z01", "Flower Chase"),
	Z02: Korok("Z02", "Race", "Ordinal Low"),
	Z03: Korok("Z03", "Light Chase"),
	Z04: Korok("Z04", "Lift Rock"),
	Z05: Korok("Z05", "Light Chase"),
	Z06: Korok("Z06", "Lift Rock", "Wood Platform"),
	Z07: Korok("Z07", "Lift Rock", "On pillar"),
	Z08: Korok("Z08", "Lift Rock Blocked", "Under rubble"),
	Z09: Korok("Z09", "Lily Pads"),
	Z10: Korok("Z10", "Lift Rock Blocked", "Under rubble"),
	Z11: Korok("Z11", "Balloon", "In tree"),
	Z12: Korok("Z12", "Lily Pads", "Drown"),
	Z13: Korok("Z13", "Race", "Ordinal Delay"),
	Z14: Korok("Z14", "Confetti", "Top of tree"),
	Z15: Korok("Z15", "Block Puzzle"),
	Z16: Korok("Z16", "Confetti"),
	Z17: Korok("Z17", "Confetti", "Top of ZD"),
	Z18: Korok("Z18", "Block Puzzle"),
	Z19: Korok("Z19", "Boulder Golf", "Magnesis"),
	Z20: Korok("Z20", "Flower Chase"),
	Z21: Korok("Z21", "Rock Circle", "Near water"),
	Z22: Korok("Z22", "Lift Rock", "On hill"),
	Z23: Korok("Z23", "Well"),
	Z24: Korok("Z24", "Flower Chase", "Stay Grounded"),
	Z25: Korok("Z25", "Lift Rock", "On ledge"),
	Z26: Korok("Z26", "Lift Rock", "Peak"),
	Z27: Korok("Z27", "Block Puzzle"),
	Z28: Korok("Z28", "Lift Rock Blocked", "Under rubble"),
	Z29: Korok("Z29", "Rock Circle"),
	Z30: Korok("Z30", "Rock Circle"),
	Z31: Korok("Z31", "Basketball"),
	Z32: Korok("Z32", "Rock Circle", "Below bridge"),
	Z33: Korok("Z33", "Light Chase"),
	Z34: Korok("Z34", "Lift Rock", "Peak"),
	Z35: Korok("Z35", "Lift Rock Blocked", "Under rubble"),
	Z36: Korok("Z36", "Lift Rock Blocked", "Under rubble"),
	Z37: Korok("Z37", "Lift Rock", "middle of thorns"),
	Z38: Korok("Z38", "Well"),
	Z39: Korok("Z39", "Light Chase"),
	Z40: Korok("Z40","Acorn", "Hanging from tree"),
	Z41: Korok("Z41", "Rock Circle"),
	Z42: Korok("Z42", "Balloon", "Shoot from above"),
	Z43: Korok("Z43", "Block Puzzle"),
	Z44: Korok("Z44", "Light Chase"),
	Z45: Korok("Z45", "Light Chase"),
	Z46: Korok("Z46", "Block Puzzle"),
	Z47: Korok("Z47", "Lift Rock Blocked", "Under boulder"),
	Z48: Korok("Z48", "Light Chase"),
	Z49: Korok("Z49", "Match Tree", "left tree"),
	Z50: Korok("Z50", "Light Chase"),
	Z51: Korok("Z51", "Rock Circle"),
	Z52: Korok("Z52", "Lift Rock Blocked", "Under leaves"),
	Z53: Korok("Z53", "Flower Chase", "In cave"),
	Z54: Korok("Z54", "Lift Rock Blocked", "Under rubble"),
	Z55: Korok("Z55", "Lift Rock"),
	Z56: Korok("Z56", "Basketball", "On stone"),
	Z57: Korok("Z57", "Lift Rock Blocked", "Under slab"),
	Z58: Korok("Z58", "Balloon", "In cave"),
	Z59: Korok("Z59", "Flower Chase", "Start in forest"),
	Z60: Korok("Z60", "Offer Apple", "In cave"),
	Z61: Korok("Z61", "Flower Chase"),
	Z62: Korok("Z62", "Rock Circle", "During flower chase"),

};