import { ability, Boss, detail, Discover, indent, Korok, Memory, Shop, Shrine, ShrineSword, Snap, split, step } from "../create";
import { cps, emy, fury, gale, important, npc, sm, txt} from "../types";
import { wb } from "../windbomb";

export const RotaOoh = [
	step(wb(cps)("N> Turn")),
	Korok("G36", "Well"),
	step(cps("SE")),
	Korok("W20", "Confetti", "In tree"),
	Korok("W21", "Block Puzzle"),
	step(wb(cps)(".S")),
	Korok("W27", "Balloon", "2 Bomb Arrows (No BT)"),
	step(wb(cps)(".E Turn")),
	Korok("W22", "Balloon"),
	step(wb(cps)(".N")),
	Korok("P14", "Block Puzzle"),
	ability(step(gale(), " + ", wb(cps)("N")), {gale: 1}),
	Korok("P07", "Ice Block"),
	step("SQ to bridge"),
	Korok("P08", "Confetti", "Cryo log"),
	step("SQ down waterfall"),
	Korok("C89", "Basketball", "GG throw"),
	step(wb(cps)("NW")),
	ShrineSword("Dah Kaso"),
	split("-"),

	step(cps("S")),
	ability(Boss("Blue Hinox", txt("3 Hits SLAM ", fury())), {fury: 1}),
	"Run",
	Korok("C88", "Lily Pads", "Cryo Block"),

	step(wb(cps)("<N")),
	Korok("G29", "Block Puzzle"),
	step(wb(cps)(".E Turn")),
	Korok("C87", "Basketball"),
	step(wb(cps)("E> High")),
	Korok("C86", "Lift Rock"),
	step(wb(cps)("<E High")),
	Korok("R80", "Lift Rock"),
	step(wb(cps)("NE")),
	Korok("C85", "Lift Rock (Tree)"),
	step(wb(cps)("E>> TS")),
	Korok("P03", "Block Puzzle"),
	step(wb(cps)("N super")),
	Korok("C80", "Acorn in Log", "Shoot midair"),
	step(wb(cps)(".E midair")),
	Korok("C79", "Lift Rock"),
	step("SQ"),
	Korok("C74", "Lift Rock", "Top of Coliseum"),
	Snap(emy("Silver Lynel"), "SNAP Elite"),
	"Drop down",
	Korok("C73", "Race", "SQ High"),
	detail(
		Korok("C68", "Acorn", "Hanging on bridge"),
		"Aim at black dot on bridge. Acorn is unloaded during rain so you need to WB to bridge first"),
	step("SQ to bridge"),
	Discover("Aquame Bridge"),
	Korok("C67", "Lift Rock", "On ledge (Hard to see)"),
	step(wb(cps)(".W Turn")),
	Korok("C66", "Rock Circle"),
	step(wb(cps)("<N Turn")),
	Korok("C58", "Tree Stump"),
	step(cps("SW")),
	Korok("C59", "Basketball", "Cryo block"),
	indent(sm("throw from lower level")),
	step(cps("<N")),
	Korok("R74", "Lift Rock"),
	ability(step(gale(), " + ", wb(cps)("<N midair")),{gale: 1}),
	Memory("Sanidin Park"),
	split("-"),
    
	step("SQ to white horse"),
	"Ride to tree",
	Korok("R79", "Offer Apple"),
	step("Ride to stable"),
	txt(npc("Register "), "(2111 name)"),
	"Talk",
	indent(npc("Meat Guy")),
	indent(npc("Horse Guy")),
	detail(
		Shop("Beedle", "Frogs/Crickets if need"),
		"DO NOT GIVE HIM BEETLE"),
	txt("Talk to ", npc("Lady under tree")),
	important("DO NOT GIVE BEETLE"),
	step("Run"),
	Korok("C78", "Lift Rock"),
	step(wb(cps)("<W to shrine")),
	Shrine("Rota Ooh"),
	split("-"),

];