import { ability, Boss, detail, Discover, Korok, Memory, Shrine, split, step, VariableChange } from "../create";
import { cps, fury, important, itm, txt, v } from "../types";
import { wb } from "../windbomb";

export const ReeDahee = [
	step(wb(cps)(".E Turn")),
	Korok("D27", "Lift Rock", "Under bridge"),
	step("SQ"),
	Korok("D34", "Lift Rock"),
	Korok("D33", "Block Puzzle"),
	step(cps("W")),
	Korok("D32", "Basketball"),
	step(wb(cps)("S")),
	Korok("D31", "Boulder Golf"),
	step(wb(cps)("S>")),
	Korok("D44", "Lift Rock"),
	step(wb(cps)("<W Turn")),
	Korok("P12", "Lift Rock (Door)"),
	"Drop",
	Korok("P13", "Lift Rock (Door)"),
	step(wb(cps)("N> Turn")),
	Discover("Outpost Ruins"),
	VariableChange({rushroom: 7}),
	detail(
		itm("7 Rushrooms"),
		txt(v("rushroom"), "/55")),
	step(wb(cps)("S")),
	ability(Boss("Luminous Talus", fury()), {fury: 2}),
	step("SQ ", cps("S")),
	Korok("D43", "Flower Count", "In cave"),
	step(wb(cps)("<S + E")),
	important("EQUIP ZORA"),
	Korok("L03", "Block Puzzle", "Use Zora Armor"),
	step(wb(cps)("<S Turn")),
	"Place cryo block",
	Korok("L10", "Lily Pads", "No Drown"),
	step(wb(cps)("<E")),
	Korok("L11", "Tree Stump"),
	step(wb(cps)("<S Turn")),
	Korok("L16", "Boulder Golf", "Bomb down stasis"),
	step(wb(cps)("N to tree stump")),
	VariableChange({rushroom: 5}),
	detail(
		itm("5 Rushrooms"),
		txt("Land on top and knock down with blizzard rod. ", v("rushroom"), "/55")),
	Korok("L05", "Flower Chase"),
	"Surf down",
	Korok("L06", "Light Chase"),
	step(wb(cps)("NW")),
	Korok("L02", "Lift Rock", "In big tree stump"),
	"Run",
	detail(
		ability(Boss("Stone Talus", fury()), {fury: 1}),
		"Fury from well korok"),
	Korok("L01", "Well"),
	step(wb(cps)("S>>")),
	Korok("L04", "Tree Stump"),
	step(wb(cps)(".N Turn")),
	Memory("West Necluda"),
	split("-"),

	step(Korok("D45", "Confetti")),
	step(wb(cps)("NE")),
	Korok("D35", "Balloon"),
	step(wb(cps)("<E Turn")),
	Korok("D36", "Flower Chase"),
	step(wb(cps)("<S")),
	Korok("D46", "Match Tree", "Right tree"),
	step(wb(cps)("N> Turn")),
	Korok("D37", "Boulder Golf"),
	Korok("D38", "Lift Rock", "In cave"),
	step(wb(cps)("E> No Turn")),
	Korok("D47", "Balloon"),
	step(wb(cps)("<E Turn")),
	Korok("D39", "Flower Chase", "Across River"),
	step(wb(cps)("W. Turn")),
	Shrine("Ree Dahee"),
	split("-"),
];