import { step, Korok, ability, MakeTOD, Boss, VariableChange, detail, Equipment, ShrineBlessing, split, ShrineDoubleSword, Chest, indent, Warp, Section } from "../create";
import { cps, gale, important, txt, fury, itm, v, rne, npc, emy } from "../types";
import { wb } from "../windbomb";

export const Eventide = [
	Section("EVENTIDE"),
	Warp("Hateno Tower"),
	split("-"),
	step(wb(cps)("W")),
	Korok("D53", "Lily Pads", "Put cryo"),
	step(wb(cps)("W + S")),
	Korok("D58", "Acorn Flying", "Bomb Arrow"),
	ability(step(gale(), " + ", wb(cps)("S>>")), {gale: 1}),
	Korok("D57", "Lily Pads", "No Drown"),
	step(wb(cps)("<S")),
	Korok("F07", "Light Chase"),
	MakeTOD("9pm", "Make Night no rain"),
	step(wb(cps)("SW")),
	Korok("F13", "Lift Rock", "Under tree"),
	step(wb(cps)("E>>")),
	important("EQUIP ATK B4 Hinox"),
	ability(Boss("Black Hinox", txt("5 Hits SLAM ", fury())), {fury: 1}),
	important("EQUIP STEALTH"),
	VariableChange({beetle: 2}),
	itm("Check trees for 2 beetles"),
	"Pedestal 1",
	step(wb(cps)("<E Turn")),
	Korok("F14", "Lily Pads", "No Drown"),
	"Check trees",
	important("CHECK 15 BEETLES"),
	ability(Boss("Red Hinox", txt("1 Hit SLAM")), {fury: 1}),
	Equipment("Bow", "If needed for smuggle"),
	"Pedestal 2",
	important("READ STONE"),
	VariableChange({honey: 5}),
	"SQ to honey",
	itm("4 Honey"),
	ability(Boss("Blue Hinox", txt("3 Hits SLAM ", fury())), {fury: 1}),
	detail(
		itm("1 Honey"),
		txt(v("honey"), "/16")),
	important("READ STONE"),
	"Pedestal 3",
	important("READ STONE"),
	ShrineBlessing("Tawa Jinn"),
	split("-"),

	important("READ STONE"),
	step(wb(cps)("E> Turn")),
	Korok("F22", "Flower Chase", "Round trip"),
	step(wb(cps)("NE")),
	Korok("F18", "Lift Rock Blocked", "Under rubble in cave"),
	"Run",
	Korok("N64", "Match Tree", txt("Right tree", rne("STS"), " BA")),
	Boss("Red Hinox", "5 Shots from above"),
	step(wb(cps)("S + S midair")),
	Korok("F32", "Light Chase"),
	step(wb(cps)("E Turn + E")),
	ShrineDoubleSword("Muwo Jeem"),
	split("-"),

	step("Run down ledge"),
	Korok("F33", "Lift Rock", "On ledge"),
	step(wb(cps)("W> down")),
	Korok("N65", "Rock Circle"),
	step(wb(cps)("N> Turn")),
	Korok("N61", "Rock Circle"),
	step(wb(cps)("E Turn")),
	npc("Talk to Kass"),
	Chest("300 Rupees", "Quest"),
	step(wb(cps)("<N Turn")),
	Korok("N60", "Basketball", "Cryo GG Throw"),
	step(wb(cps)("E> Turn over bay")),
	Korok("N62", "Flower Chase", "Start on beach"),
	step(wb(cps)("N")),
	detail(
		ability(txt(emy("All Enemies "), fury()), {fury: 1}),
		"Make sure chest unlocks"),
	step(wb(cps)("NE")),
	Korok("N54", "Offer Palm Fruit", "In cave"),
	step(wb(cps)("E> Turn")),
	ability(Boss("Luminous Talus", fury()), {fury: 2}),
	Korok("N56", "Lily Pads", "Cryo block wb"),
	"SQ DEFUSE",
	Korok("N63", "Rock Circle", "3"),
	"SQ to flower",
	Korok("N57", "Flower Chase"),
	step(wb(cps)("W>")),
	Korok("N55", "Balloon", "Turn Right"),
	detail(
		step(wb(cps)("SW + S> midairs")),
		"Watch strong wind"),
	ShrineDoubleSword("Chaas Qeta"),
	split("-"),

	step(Korok("N66", "Race")),
	"WB to Eventide",
	"Smuggle:",
	indent("Arrow x4"),
	indent("Tree Branch"),
	indent("GEB"),
	step(wb(cps)("SE to camp")),
	"Carry Orb 1 to Pedestal",
	step(wb(cps)("S")),
	ability(Boss("Blue Hinox", txt("GEBx3 + ", fury())), {fury: 2}),
	Equipment("Boko Club"),
	detail(
		"Carry Orb 2 to camp",
		"Blow up metal boxes with bomb while carrying the orb and use Daruk's Protection"),
	step(wb(cps)("E to 3rd orb")),
	"Use boko club to hit the slab",
	step(wb(cps)("E to shrine")),
	ShrineBlessing("Korgu Chideh"),
	split("-"),
];