import { step, Korok, detail, ability, Boss, ChestSpecial, split, Tower, VariableChange, Shrine } from "../create";
import { cps, fury, gale, itm, txt, v } from "../types";
import { wb } from "../windbomb";

export const ShodaSah = [
	ability(step(gale(), " + ", cps("N midairs")), {gale: 1}),
	Korok("F02", "Race", "<S Turn"),
	step(wb(cps)("N.")),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("SE")),
	Korok("F05", "Balloon"),
	step(wb(cps)("NW")),
	Korok("F01", "Acorn", "In tree"),
	step(wb(cps)("S> Turn")),
	Korok("F04", "Rock Circle", "Use tree"),
	"Glide",
	Korok("F03", "Balloon"),
	"Shield jump over",
	ChestSpecial("Zant Helm"),
	step(wb(cps)(".S")),
	Boss("Red Hinox", "5 BA (rain OK)"),
	step(wb(cps)("<S midair")),
	Korok("F10", "Flower Chase", "In cave"),
	step(wb(cps)("E>> Turn")),
	ability(Korok("F16", "Race", gale()), {gale: 1}),
	step(wb(cps)("<W Turn")),
	Korok("F15", "Light Chase"),
	ability(step(gale(), " + ", cps("E>")), {gale: 1}),
	Boss("Red Hinox", "5 BA (rain OK)"),
	step(wb(cps)("S> midair")),
	Korok("F25", "Offer Durian"),
	step(wb(cps)("SW")),
	Tower("Faron Tower"),
	split("-"),
    
	step(wb(cps)("<S Turn")),
	Korok("F39", "Offer Durian"),
	step("Run"),
	Korok("F40", "Lift Rock", "middle of mud"),
	step(wb(cps)("S Turn right")),
	Korok("F54", "Lift Rock", "Ledge beach level"),
	step("SQ to rock circle"),
	Korok("F53", "Rock Circle"),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("E>")),
	Korok("F56", "Balloon", "Under cliff"),
	step(wb(cps)("E midairs")),
	detail(
		ability(txt(fury(), " + kill the camp"), {fury: 1}),
		"make sure chest unlocks. Need to manually kill the black boko"),
	step(wb(cps)("N + N midair")),
	Korok("F43", "Rock Circle"),
	ability(step(gale(), " + ", wb(cps)("<W + <W")), {gale: 1}),
	Korok("F55", "Lift Rock", "Upper ledge"),
	step(wb(cps)("NW SQ")),
	Korok("F48", "Offer Banana", "banana next to it"),
	step(wb(cps)("N> Turn to lake")),
	"Shock fish",
	VariableChange({heartyBass: 5}),
	detail(
		itm("5 Hearty Bass"),
		txt(v("heartyBass"), "/15")),
	itm("Hyrule Bass until 12"),
	step(wb(cps)("W")),
	Boss("Stone Talus", "Shoot weakness midair"),
	step(wb(cps)("N midair")),
	ability(Korok("F28", "Flower Chase", gale()), {gale: 1}),
	step(wb(cps)("N watch bomb slipping")),
	Korok("F27", "Lift Rock", "Ledge"),
	step(wb(cps)("N")),
	Shrine("Shoda Sah"),
	split("-"),
	
];