import { step, Korok, detail, ability, Discover, Boss, ChestSpecial, split, Tower, MakeTOD, VariableChange, Shrine } from "../create";
import { cps, fury, gale, important, itm, npc, rne, txt, v } from "../types";
import { wb } from "../windbomb";

export const ShodaSah = [
	step(wb(cps)("W")),
	Korok("L13", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("<W Turn")),
	detail(
		Korok("L17", "Light Chase"),
		"L17 and L18 are at the same location"),
	Korok("L18", "Light Chase"),
	step("SQ ", cps("N>"), " down"),
	Korok("L12", "Block Puzzle", "Piece on tree"),
	step(cps("S")),
	Korok("L28", "Flower Count", "On peak"),
	step(wb(cps)("E")),
	Korok("L29", "Lift Rock", "Peak"),
	step(wb(cps)("E> Turn")),
	Korok("L34", "Boulder Circle", "STS Jump ATK down"),
	step(wb(cps)("<W")),
	Korok("L35", "Match Tree",txt("Right, ", "2 durians")),
	step(wb(cps)("S no turn")),
	Korok("L45", "Lift Rock"),
	step("SQ to creek DEFUSE"),
	Korok("L54", "Lily Pads", "No Drown"),
	step(wb(cps)("E")),
	Discover("Zonai Ruins"),
	Korok("L56", "Boulder Circle", rne("STS + Magnesis")),
	txt("SQ to ", npc("Kass")),
	"Run up",
	Korok("L57", "Light Chase"),
	step(wb(cps)(".E Turn")),
	Korok("L58", "Light Chase"),
	step(wb(cps)("N")),
	Korok("L46", "Lift Rock", "Top of small waterfall"),
	ability(step(gale(), " + ", cps("N midairs")), {gale: 1}),
	Korok("F02", "Race", "<S Turn"),
	step(wb(cps)("N.")),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("SE")),
	Korok("F05", "Balloon"),
	step(wb(cps)("NW")),
	Korok("F01", "Acorn", "In tree"),
	step(wb(cps)("S> Turn")),
	Korok("F04", "Rock Circle", "Use tree"),
	"Glide",
	Korok("F03", "Balloon"),
	"Shield jump over",
	ChestSpecial("Zant Helm"),
	step(wb(cps)(".S")),
	Boss("Red Hinox", "5 BA (rain OK)"),
	step(wb(cps)("<S midair")),
	Korok("F10", "Flower Chase", "In cave"),
	step(wb(cps)("E>> Turn")),
	ability(Korok("F16", "Race", gale()), {gale: 1}),
	step(wb(cps)("<W Turn")),
	Korok("F15", "Light Chase"),
	ability(step(gale(), " + ", cps("E>")), {gale: 1}),
	Boss("Red Hinox", "5 BA (rain OK)"),
	step(wb(cps)("S> midair")),
	Korok("F25", "Offer Durian"),
	step("SQ HIGH to tower DEFUSE"),
	Tower("Faron Tower", "84.10%"),
	split("-"),
    
	step(wb(cps)("<S Turn")),
	Korok("F39", "Offer Durian"),
	step("SQ ", cps("E.")),
	Korok("F40", "Lift Rock", "middle of mud"),
	step(wb(cps)("E> super")),
	Korok("F48", "Offer Banana", "banana next to it"),
	step(wb(cps)("E>")),
	Korok("F55", "Lift Rock", "Upper ledge"),
	step(wb(cps)("W Turn")),
	Korok("F54", "Lift Rock", "Ledge beach level"),
	step("SQ to rock circle"),
	Korok("F53", "Rock Circle"),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("E>")),
	Korok("F56", "Balloon", "Under cliff"),
	step(wb(cps)("E midairs")),
	detail(
		ability(txt(fury(), " the camp"), {fury: 2}),
		"make sure chest unlocks"),
	MakeTOD("9pm", "Make Night", "if before 6PM"),
	step(wb(cps)("N + N midair")),
	Korok("F43", "Rock Circle"),
	step(wb(cps)("NW to lake")),
	"Shock fish",
	VariableChange({heartyBass: 5}),
	detail(
		itm("5 Hearty Bass"),
		txt(v("heartyBass"), "/15")),
	itm("Hyrule Bass until 12"),
	step(wb(cps)("S. Turn")),
	Korok("F46", "Block Puzzle", "Piece in waterfall"),
	step(wb(cps)("<N")),
	Korok("F42", "Balloon", "Middle of bridge"),
	important("EQUIP STEALTH"),
	step(wb(cps)("W> to beetle")),
	VariableChange({beetle: 5}),
	detail(
		itm("5 beetles"),
		txt(v("beetle"), "/15")),
	ability(txt(gale(), " tree stump"), {gale: 1}),
	detail(
		Korok("F34", "Balloon", "3"),
		"Behind leaf in front; Far in the back behind; Below to the north"),
	important("EQUIP ATK 2 + ZORA"),
	step(wb(cps)("E")),
	Boss("Stone Talus", "Shoot weakness midair"),
	step(wb(cps)("N")),
	ability(Korok("F28", "Flower Chase", gale()), {gale: 1}),
	step(wb(cps)("N watch bomb slipping")),
	Korok("F27", "Lift Rock", "Ledge"),
	step(wb(cps)("N")),
	Shrine("Shoda Sah"),
	split("-"),
];