import { ability, Boss, Chest, detail, Korok, MakeTOD, Shrine, ShrineBlessing, Snap, split, step, VariableChange, Warp } from "../create";
import { cps, fury, gale, important, itm, npc, txt, v } from "../types";
import { wb } from "../windbomb";

export const Lurelin = [
	step(wb(cps)("S")),
	Korok("F19", "Race", "Swim up"),
	wb(cps)("N midair "),
	Korok("F17", "Well", "(Mag boulder in stone)"),
	step(wb(cps)("E> Turn")),
	Korok("F20", "Match Tree", "Closest"),
	step(wb(cps)("E")),
	Korok("F21", "Offer Apple"),
	"Unequip metal",
	step(wb(cps)("<W Turn")),
	Korok("F29", "Block Puzzle", "Piece in lake, cryo"),
	"Equip metal",
	npc("Kass"),
	MakeTOD("9pm", "Make Night if need"),
	ShrineBlessing("Qukah Nata"),
	split("-"),

	step(wb(cps)("E> TS")),
	npc("Love Quest Guy Twice"),
	npc("Love Quest Lady Twice"),
	step(wb(cps)("S")),
	Korok("F47", "Lift Rock", "Peak"),
	step(wb(cps)("S> Turn")),
	Korok("F57", "Rock Circle", "Heart"),
	step(wb(cps)("E> Turn")),
	"Land on pillar",
	"Cryo middle",
	Chest("Sapphire", "Eastern most chest"),
	step(wb(cps)("NW")),
	Korok("F49", "Rock Circle"),
	step(wb(cps)("E")),
	Korok("F50", "Flower Chase", "Turn around after beach"),
	step(wb(cps)("SE")),
	Korok("F58", "Lily Pads", "Close to beach rocks"),
	step(wb(cps)("NE")),
	Korok("F51", "Lily Pads"),
	step(wb(cps)("E Turn")),
	Korok("F52", "Lift Rock"),
	Snap("Shards", "SNAP Quest"),
	Shrine("Kah Yah"),
	split("-"),
    
	ability(step(gale(), " + ", wb(cps)("W")), {gale: 1}),
	Korok("F37", "Lily Pads", "No Drown"),
	"Run to talus",
	ability(Boss("Stone Talus", txt(fury(), " from top")), {fury: 1}),
	step(wb(cps)("<W Turn")),
	Korok("F45", "Flower Chase", "Top of house"),
	"Drop down south",
	itm("Blueshell Snail"),
	"SQ to leftmost house",
	npc("Talk to Mom Twice"),
	MakeTOD("9pm", "Make Night", "For beetle & 2 stalnox"),
	detail(
		npc("Talk to Dad"),
		"In house if rain"),
	Korok("F44", "Apple", "Bomb top of palm tree"),
	detail(
		npc("Old man (2) Talk again"),
		"In house if rain"),
	detail(
		step(wb(cps)("N>")),
		txt("NE if rain")),
	Korok("F36", "Rock Circle", "STS tree"),
	step(wb(cps)("W>")),
	important("EQUIP ATK UP"),
	Shrine("Yah Rin"),
	split("-"),

	step(wb(cps)("W>")),
	Korok("F31", "Lift Rock Blocked", "Under leaves"),
	step(wb(cps)("W super")),
	Korok("F30", "Match Tree", "West tree"),
	step(wb(cps)("SW")),
	ability(Boss("Stalnox", txt("GEBx6 + ", fury())), {fury: 1}),
	step(wb(cps)("<W super")),
	Korok("F46", "Block Puzzle"),
	step(wb(cps)("<N")),
	Korok("F42", "Balloon", "Middle of bridge"),
	important("EQUIP STEALTH"),
	step(wb(cps)("W> to beetle")),
	VariableChange({beetle: 5}),
	detail(
		itm("5 beetles"),
		txt(v("beetle"), "/15")),
	"Run + Climb to pinwheel",
	detail(
		Korok("F34", "Balloon", "3"),
		"Behind leaf in front; Far in the back behind; Below to the north"),

];