import { step, Korok, ability, MakeTOD, Boss, VariableChange, detail, Equipment, ShrineBlessing, split, ShrineDoubleSword, Chest, indent, Warp } from "../create";
import { cps, emy, fury, gale, important, itm, npc, rne, txt, v } from "../types";
import { wb } from "../windbomb";

export const Eventide = [
	step(wb(cps)("W")),
	Korok("D53", "Lily Pads", "Put cryo"),
	step(wb(cps)("W + S")),
	Korok("D58", "Acorn Flying", "Bomb Arrow"),
	ability(step(gale()), {gale: 1}),
	Korok("D57", "Lily Pads", "No Drown"),
	step(wb(cps)("<S")),
	Korok("F07", "Light Chase"),
	MakeTOD("9pm", "Make Night no rain"),
	step(wb(cps)("SW")),
	Korok("F13", "Lift Rock", "Under tree"),
	step(wb(cps)("E>>")),
	important("EQUIP ATK B4 Hinox"),
	ability(Boss("Black Hinox", txt("5 Hits SLAM ", fury())), {fury: 1}),
	important("EQUIP STEALTH"),
	VariableChange({beetle: 2}),
	itm("Check trees for 2 beetles"),
	"Pedestal 1",
	step(wb(cps)("NE")),
	VariableChange({heartyBass: 5}),
	detail(
		itm("5 Hearty Bass"),
		txt(v("heartyBass")," /15")),
	important("CHECK 15 HEATY BASS"),
	ability(step(gale(), " + ", cps("S>")), {gale: 1}),
	Korok("F14", "Lily Pads", "No Drown"),
	"Check trees",
	detail(
		Boss("Red Hinox", txt("9 Hits NO SLAM")),
		"6 Hits with ATK up. Only if you already have enough beetles"),
	Equipment("Bow", "If needed for smuggle"),
	"Pedestal 2",
	important("READ STONE"),
	VariableChange({honey: 6}),
	"Check trees",
	itm("4 Honey"),
	important("EQUIP ATK 3"),
	ability(Boss("Blue Hinox", txt("3 Hits SLAM ", fury())), {fury: 1}),
	detail(
		itm("2 Honey"),
		txt(v("honey"), "/16")),
	important("READ STONE"),
	"Pedestal 3",
	important("READ STONE"),
	important("CHECK 13 BEETLES"),
	ShrineBlessing("Tawa Jinn"),
	split("-"),
	important("READ STONE"),
	step(wb(cps)("E> Turn")),
	Korok("F22", "Flower Chase", "Round trip"),
	step(wb(cps)("NE")),
	Korok("F18", "Lift Rock Blocked", "Under rubble in cave"),
	"Run",
	Korok("N64", "Match Tree", txt("Right tree", rne("STS"), " BA")),
	Boss("Red Hinox", "5 Shots from above"),
	step(wb(cps)("S + S midair")),
	Korok("F32", "Light Chase"),
	step(wb(cps)("E Turn + E")),
	ShrineDoubleSword("Muwo Jeem"),
	split("-"),

	step("Run down ledge"),
	Korok("F33", "Lift Rock", "On ledge"),
	step(wb(cps)("W> down")),
	Korok("N65", "Rock Circle"),
	step(wb(cps)("N> Turn")),
	Korok("N61", "Rock Circle"),
	step(wb(cps)("E Turn")),
	npc("Talk to Kass"),
	Chest("300 Rupees", "Quest"),
	step(wb(cps)("<N Turn")),
	Korok("N60", "Basketball", "2 Cryo Block GG"),
	step(wb(cps)("E> Turn over bay")),
	Korok("N62", "Flower Chase", "Start on beach"),
	step(wb(cps)("N")),
	detail(
		ability(txt(emy("All Enemies "), fury()), {fury: 1}),
		"Make sure chest unlocks"),
	step(wb(cps)("NE")),
	Korok("N54", "Offer Palm Fruit", "In cave"),
	step(wb(cps)("E> Turn")),
	ability(Boss("Luminous Talus", fury()), {fury: 2}),
	Korok("N56", "Lily Pads", "Cryo block wb"),
	"SQ DEFUSE",
	Korok("N63", "Rock Circle", "3"),
	"SQ to flower",
	Korok("N57", "Flower Chase"),
	step(wb(cps)("W> Slight Turn")),
	Korok("N55", "Balloon", "Turn Right"),
	detail(
		step(wb(cps)("SW + S> midairs")),
		"Watch strong wind"),
	ShrineDoubleSword("Chaas Qeta"),
	split("-"),

	step(Korok("N66", "Race")),
	"WB to Eventide",
	"Smuggle:",
	indent("Arrow"),
	indent("Tree Branch"),
	indent("Bow"),
	detail(
		ability(Boss("Blue Hinox", fury()), {fury: 3}),
		"Fury with tree branch and take his weapon"),
	ShrineBlessing("Korgu Chideh"),
	split("-"),

	Warp("Dueling Peaks Tower"),
	split("-"),

];