import { Chest, emy, fury, Koroks, Npc, Shrines, SnapQuest, WindbombStepCps } from "../../engine";

export const KahYah = [
	WindbombStepCps("<S Turn"),
	Koroks.F39,
	WindbombStepCps("SQ"),
	Koroks.F40,
	WindbombStepCps("E> + <S"),
	Koroks.F48,
	WindbombStepCps("<S"),
	Koroks.F55,
	WindbombStepCps("NE"),
	Koroks.F43,
	WindbombStepCps("E + E"),
	Npc("Love Guy", "Twice"),
	Npc("Love Lady", "Twice"),
	WindbombStepCps("S."),
	Koroks.F47,
	WindbombStepCps("<<W Ordinal DT"),
	{
		text: emy(fury(), " kill camp"),
		ability: { fury: 3 }
	},
	WindbombStepCps("<E Turn"),
	Koroks.F57,
	WindbombStepCps("E Turn"),
	"Cryo middle",
	Chest("Sapphire", "For Quest"),
	WindbombStepCps("NW"),
	Koroks.F49,
	WindbombStepCps("E"),
	Koroks.F50,
	WindbombStepCps("SE"),
	Koroks.F58,
	WindbombStepCps("NE"),
	Koroks.F51,
	WindbombStepCps("N"),
	SnapQuest("Shard 1"),
	WindbombStepCps("E> Turn"),
	SnapQuest("Shard 2"),
	Koroks.F52,
	WindbombStepCps("NW"),
	SnapQuest("Shard 3"),
	Shrines.KahYah
];