import { step, Korok, split, MakeTOD, ShrineBlessing, ability, Boss, Equipment, Tower, detail } from "../create";
import { cps, emy, fury, gale, important, itm, txt } from "../types";
import { wb } from "../windbomb";

export const DilaMaag = [
	step("Run down bridge"),
	Korok("W33", "Balloon", "Under bridge"),
	step(wb(cps)("W midair")),
	Korok("W32", "Block Puzzle"),
	"Run to ledge",
	Korok("W31", "Lift Rock"),
	step("Run + ", wb(cps)("N. to tower")),
	Tower("Wasteland Tower"),
	split("-"),

	step(wb(cps)("N> Turn down")),
	Korok("W12", "Acorn", "Bomb midair"),
	txt("Freeze ", emy("Electric Lizalfos")),
	itm("Electric Darner"),
	Korok("W16", "Boulder Golf", "2 MS Hits"),
	step("SQ to tree DEFUSE"),
	Korok("W11", "Lift Rock (Tree)"),
	Equipment("Fire Rod"),
	"Cut Tree",
	wb(cps)(".S Turn"),
	"Start race",
	Korok("W24", "Lift Rock", "On platform"),
	Korok("W23", "Race", "Drop down finish race"),
	step(wb(cps)("E. + S + S DEFUSE")),
	Korok("W34", "Rock Circle"),
	step(wb(cps)("E>> Turn")),
	Korok("W41", "Lift Rock", "On overpass"),
	step(wb(cps)("W. Turn")),
	Korok("W39", "Block Puzzle"),

	step(wb(cps)("W. Turn")),
	Korok("W38", "Lift Rock", "On pillar"),
	detail(
		step(wb(cps)("<<S")),
		"Aim at middle pillar"),
	MakeTOD("12pm", important("Make Noon")),
	ability(Boss("Luminous Talus", fury()), {fury: 3}),
	important("BURN OUT FURY"),
	step(cps("S> Turn")),
	Korok("W48", "Block Puzzle"),
	step(wb(cps)("E + E midair")),
	Korok("W49", "Block Puzzle"),
	step(wb(cps)("E + NE midair")),
	Korok("W46", "Lift Rock Blkd", "Corner"),
	ability(gale(), {gale: 1}),
	Korok("W45", "Rock Circle"),
	step(wb(cps)("<W Turn + W midair")),
	Korok("W50", "Lift Rock", "Top of big pillar"),
	step(wb(cps)("S> Turn to race start")),
	Korok("W58", "Race", wb(cps)("S Turn")),
	step(wb(cps)("NE")),
	ShrineBlessing("Dila Maag"),
	split("-"),
];