import { Boss, Chest, ChestSpecial, detail, Discover, Equipment, Korok, MakeTOD, Memory, Shrine, Snap, split, step, VariableChange } from "../create";
import { txt, emy, important, rne, v, lcn, gale, itm, cps, fury } from "../types";
import { wb } from "../windbomb";

export const CastleSecondHalf = [
	step("Wood boxes behind shrine"),
	VariableChange({tail: 3}),
	txt("Sneakstrike ", emy("Lizalfos")),
	Chest("Star Fragment", "Magnesis out"),
	important("SWITCH ", rne("BOMBS")),
	detail(
		txt("Kill 2 more ", emy("Lizalfos")),
		txt("Tails ", v("tail"), "/45")),
	"Run outside",
	Korok("X01", "Lift Rock", "On ledge"),
	step("WB aim big sheika pillar"),
	Korok("X04", "Balloon", "BA BT"),
	txt("Drop down to ", lcn("Lock up")),
	"Shoot eye far",
	VariableChange({tail: 1}),
	detail(
		emy("Black Lizalfos"),
		txt(v("tail"), "/45")),
	Equipment("Blizzard Rod"),
	"Run to stalnox",
	Boss("Stalnox", "GEB"),
	Chest("Hylian Shield"),
	detail(
		Equipment("Thunderblade"),
		"For DLC shrine and OHO overloading"),
	step("Run toward West Passage"),
	"Break boxes",
	Korok("X13", "Offer Egg"),
	detail(
		step("Run to water room"),
		"Watch out for the moblin with Royal Guard Spear. Might want to consider freeze him with blizzard rod"),
	gale("1"),
	Korok("X08", "Lift Rock", "Wooden Platform"),
	step("Glide to switch room"),
	VariableChange({tail: 1}),
	detail(
		emy("Lizalfos"),
		txt("Break wall. ",v("tail"),"/45")),
	Chest("Dinraal Fang"),
	"Glide up run out",
	gale("2-3"),
	VariableChange({silentPrincess: 1}),
	detail(
		itm("Silent Princess"),
		txt(v("silentPrincess"), "/16")),
	Snap(emy("Guardian Skywatcher"), "SNAP Quest"),
	Memory("Hyrule Castle"),
	split("-"),

	step("Run"),
	Korok("X09", "Lift Rock"),
	Discover("Zelda's Room"),
	step(wb(cps)("E super")),
	Korok("X12", "Lift Rock"),
	step("Aim at Gatehouse"),
	Korok("X16", "Confetti", "Top of Second Gatehouse"),
	Discover("Second Gatehouse"),
	step(wb(cps)("W")),
	Korok("X14", "Lift Rock Blocked", "Under rubble"),
	step("Aim at shiekah pillar"),
	Korok("X17", "Confetti", "Top of First Gatehouse"),
	Discover("First Gatehouse"),
	step("Run"),
	Korok("X18", "Lift Rock", "On wall"),
	step(wb(cps)("E")),
	Korok("X23", "Balloon"),
	"Drop down to balcony",
	Korok("X21", "Shoot Emblem"),
	Discover("Observation Room"),
	Korok("X22", "Balloon", "Aim top wall in background"),
	txt("Glide ", cps("E")),
	Korok("X20", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("S>")),
	Korok("X24", "Lift Rock", "On gate"),
	"Drop down under bridge",
	Korok("C16", "Acorn"),
	important("EQUIP ROYAL GUARD"),
	Korok("X25", "Flower Chase", "Across bridge"),
];
export const ZaltaWa = [
	step(cps("S")),
	detail(
		Korok("C33", "Balloon", "On out wall"),
		"Snap Stalker if needed"),
	step(wb(cps)("S> Turn")),
	Korok("C35", "Lift Rock", "On pillar"),
	Memory("Sacred Grounds"),
	split("-"),

	step(wb(cps)("S>> Turn")),
	Korok("C43", "Acorn Flying"),
	step(cps("W>")),
	Korok("C42", "Balloon", "Shoot midair"),
	step(wb(cps)("W midair")),
	Korok("C41", "Acorn", "In tree"),
	Korok("C40", "Light Chase", "Same Forest"),
	step(cps("<W")),
	Korok("C39", "Confetti", "Top of flag pole"),
	step(wb(cps)("W Turn")),
	Korok("C38", "Flower Chase"),
	step(wb(cps)("<N Turn")),
	Boss("Black Hinox", txt(fury("1-3"), " + 2 GEB")),
	MakeTOD("9pm", "Make Night", "For BM"),
	VariableChange({tail: 1}),
	step(wb(cps)("SW")),
	detail(
		txt("Kill ", emy("Lizalfos")),
		txt(v("tail"), "/45")),
	Korok("C36", "Lift Rock"),
	itm("18 Acorns"),
	ChestSpecial("Midna's Helm", "NW of the trees"),
	step("SQ"),
	Korok("R49", "Block Puzzle"),
	step(wb(cps)("N")),
	Korok("R48", "Acorn", "In tree"),
	step(wb(cps)("NE")),
	Korok("R42", "Lift Rock", "Riverbank"),
	step(wb(cps)("NE")),
	detail(
		Korok("R45", "Flower Chase", "Start at pillar"),
		"Jump to top, recover. Grab down, get flower, Hop off glide to last"),
	Korok("R43", "Balloon", "Aim a bit above"),
	"Run to basketball",
	Korok("R44", "Basketball", "GG rock throw"),
	step(cps("N>")),
	Korok("C24", "Lift Rock", "On small hill near bridge"),
	step("SQ DEFUSE"),
	Korok("R26", "Race", cps("W")),
	Korok("R27", "Acorn", "Hanging from bridge"),
	step(cps("W")),
	Shrine("Zalta Wa", "Skip BM"),
	split("-"),
];