import { Boss, ChestSpecial, fury, Koroks, Materials, Section, txt, Warp, WindbombStepCps } from "../../engine";

export const Satori = [
	Section("SATORI"),

	Warp("Mogg Latan"),
	WindbombStepCps("N"),
	Koroks.R52,
	ChestSpecial("Ancient Bridle"),
	Materials.SilentPrincess(4),
	"Run to flower",
	Koroks.R61,
	WindbombStepCps("SQ to stalnox"),
	Boss("Stalnox", txt("1 Shot + ", fury())).extend({
		ability: { fury: 3 }
	}),
	WindbombStepCps("N"),
	Koroks.R62,
	WindbombStepCps("NE"),
	Koroks.R53,
	WindbombStepCps("SE SQ"),
	Koroks.R54,
	"Drop down",
	Koroks.R55,
	WindbombStepCps("SQ to forest down"),
	Koroks.R56,
	WindbombStepCps("SQ to tree down"),
	Koroks.R57,
	WindbombStepCps("S> + <W"),
	Koroks.R68,
	Koroks.R69,
	WindbombStepCps("S Turn"),
	Koroks.R78,
	WindbombStepCps("W"),
	Koroks.R77,
	WindbombStepCps("W + W"),
	Koroks.R75,
	Koroks.R76,
	WindbombStepCps("GALE + <E").extend({
		ability: { gale: 1 }
	}),
	Koroks.G14,
	WindbombStepCps("N> Turn"),
	Koroks.R70,
	WindbombStepCps(".W Turn"),
	Koroks.R73,
	WindbombStepCps("W"),
	Materials.Honey(2),
	WindbombStepCps("SQ to basketball"),
	Koroks.R67,
	Koroks.R66,
	Koroks.R65,
	Koroks.R64,
	WindbombStepCps("N. Turn"),
	Koroks.R51,
	WindbombStepCps("SW"),
	Koroks.R63,
	WindbombStepCps("S>"),
	Koroks.R72,
	WindbombStepCps("NW"),
	Koroks.R50,
	"Drop down",
	Koroks.R59,
	WindbombStepCps("S. Turn"),
	Koroks.R71
];