import { Boss, Chest, ChestSpecial, Discover, fury, Item, Koroks, MakeNight, MakeNoon, Materials, Memories, Npc, Shrines, WindbombStepCps } from "../../engine";

export const BalloonGirl = [
	WindbombStepCps(".S Turn"),
	Discover("Moor Garrison Ruins"),
	WindbombStepCps("W midair"),
	Koroks.Z30,
	WindbombStepCps(".W"),
	Koroks.Z29,
	WindbombStepCps("<W TS"),
	Koroks.C46,
	WindbombStepCps("SW"),
	Koroks.C51,
	WindbombStepCps("E"),
	Shrines.KayaWan,

	"Shield surf down",
	Item("4 Hyrule Bass"),
	Chest("Royal Sword", "For quest"),
	Npc("Quest Guy"),
	Discover("Wetland Stable"),
	WindbombStepCps("<S"),
	Materials.Honey(1),
	Koroks.Z37,
	WindbombStepCps("SW"),
	Memories.HyruleField,

	WindbombStepCps("<W + <W"),
	Koroks.C56,
	WindbombStepCps("N>"),
	Boss("Blue Hinox", fury()).extend({
		ability: { fury: 3 }
	}),
	WindbombStepCps("W Turn"),
	Koroks.C50.extend({
		notes: "AA the stalker (and bokos if necessary)"
	}),
	Materials.Honey(1),
	WindbombStepCps("W> Turn"),
	ChestSpecial("Tingle Pants"),
	WindbombStepCps("SQ High"),
	Koroks.C44,
	WindbombStepCps("E. Turn"),
	Koroks.C45,
	WindbombStepCps("NE"),
	Koroks.C34,
	WindbombStepCps("N SQ"),
	Boss("Blue Hinox", "5 Spin SLAM"),
	WindbombStepCps("E + E> Turn"),
	Koroks.Z21,
	WindbombStepCps("N"),
	Koroks.Z11,
	WindbombStepCps("N> Turn"),
	Koroks.C13,
	WindbombStepCps("<W Turn"),
	Koroks.K35,
	WindbombStepCps("S>> Delay to race"),
	Koroks.Z02,
	Koroks.Z03,
	WindbombStepCps("<N"),
	Koroks.K34,
	WindbombStepCps("SQ to block puzzle"),
	Koroks.K33,
	Shrines.MirroShaz,
	WindbombStepCps("<W Turn"),
	MakeNoon("For Balloon Girl"),
	Npc("Balloon Quest"),
	MakeNight("For Stalnox")
];