import { step, Korok, Discover, Shrine, Boss, split, Memory, ability, ChestSpecial } from "../create";
import { cps, fury, txt } from "../types";
import { wb } from "../windbomb";

export const MirroShaz = [
	step(wb(cps)("S>> Turn")),
	Korok("Z41", "Rock Circle"),
	"Lotus Seeds here if need",
	step("SQ to hinox DEFUSE"),
	ability(Boss("Red Hinox", txt("1 Hit SLAM ", fury())), {fury: 1}),
	step(wb(cps)("W> TS")),
	Discover("Moor Garrison Ruins"),
	step(wb(cps)("N")),
	Shrine("Sheh Rata"),
	split("-"),

	step(wb(cps)("<S Turn")),
	Korok("Z30", "Rock Circle"),
	step(wb(cps)(".W")),
	Korok("Z29", "Rock Circle"),
	step(wb(cps)("<W Turn")),
	Korok("C46", "Lift Rock", "Under bridge"),
	step(wb(cps)("S> + W")),
	Korok("C51", "Boulder Circle"),
	step(wb(cps)(".S Turn")),
	Memory("Hyrule Field"),
	split("-"),
    
	step(wb(cps)("W + <W")),
	Korok("C56", "Offer Apple"),
	step(wb(cps)("N>")),
	ability(Boss("Blue Hinox", txt("3 Hits SLAM ", fury())), {fury: 1}),
	step(wb(cps)("W Turn")),
	Korok("C50", "Flower Count", "Chaos Ranch"),
	step(wb(cps)("W> Turn")),
	ChestSpecial("Tingle Shirt", "Under decayed guardian"),
	step(wb(cps)("N>")),
	Korok("C44", "Lift Rock"),
	step(wb(cps)("E Turn")),
	Korok("C45", "Lift Rock", "On hill"),
	step(wb(cps)("NE")),
	Korok("C34", "Match Tree", "Left tree"),
	step(wb(cps)("N")),
	ability(Boss("Blue Hinox", txt("3 Hits SLAM ", fury())), {fury: 1}),
	step(wb(cps)("E + SE")),
	Korok("Z21", "Rock Circle", "Near water"),
	step(wb(cps)("N")),
	Korok("Z11", "Balloon", "In tree"),
	step(wb(cps)("N> Turn")),
	Korok("C13", "Basketball", "On bridge. Cryo"),
	step(wb(cps)("<E Turn")),
	Korok("K35", "Block Puzzle"),
	step(wb(cps)("S>")),
	Korok("Z02", "Race", "Ordinal Low"),
	Korok("Z03", "Light Chase"),
	step(wb(cps)("<N Turn")),
	Korok("K34", "Lily Pads", "No Drown"),
	step("SQ DEFUSE"),
	Korok("K33", "Block Puzzle"),
	step("SQ"),
	Shrine("Mirro Shaz"),
	split("-"),
];