import { ability, Boss, Chest, detail, Discover, Equipment, Korok, ShrineDoubleSword, ShrineSword, split, step } from "../create";
import { cps, fury, gale, npc, txt } from "../types";
import { wb } from "../windbomb";

export const KatahChuki = [
	step(wb(cps)("SW")),
	detail(
		npc("Balloon Quest"), 
		"If pass 8PM, make noon, then make night after quest"),
	step(wb(cps)("W Turn Super")),
	detail(
		Discover("Rauru Settlement Ruins"),
		"Discover on the way"),
	Discover("Helmhead Bridge"),
	step(wb(cps)("S> Turn")),
	Korok("C05", "Acorn", "In tree"),
	ability(Boss("Stalnox", txt("GEBx6 + ", fury())),{fury: 1}),
	"Surf down",
	Korok("C04", "Lift Rock", "In fountain"),
	detail(
		step(wb(cps)("<S Turn")),
		"Might want to kill the guardian if he keeps following you"),
	Korok("C10", "Basketball", "Cryo"),
	step(wb(cps)("<<E")),
	Korok("C06", "Lily Pads", "No Drown"),
	step(wb(cps)("N>")),
	Korok("C02", "Block Puzzle"),
	step(wb(cps)("E>")),
	ability(Boss("Luminous Talus", fury()),{fury: 2}),
	ability(step(gale(), " + ", cps("S")), {gale: 1}),
	"Check 2 Slots",
	detail(
		Equipment("Guardian Axe++"),
		"Blizzard rod + RGC Stunlock 4 hits"),
	Chest("Frostspear"),
	ShrineDoubleSword("Namika Ozz"),
	split("-"),

	step(wb(cps)("W DEFUSE")),
	Korok("C09", "Confetti", "Top of tree"),
	step(wb(cps)("SW")),
	Korok("C11", "Lift Rock", "Inside hollow tree"),
	step(wb(cps)("E>")),
	Korok("C12", "Lift Rock", "In tree stump on peak"),
	step(wb(cps)("<W Turn")),
	Korok("C19", "Balloon", "Pinwheel on hollow tree"),
	step(wb(cps)("<W Turn")),
	Discover("Orsedd Bridge"),
	Korok("C23", "Acorn", "Hanging below bridge"),
	step(wb(cps)("NW")),
	Korok("C18", "Light Chase"),
	step(cps("W super")),
	Korok("C17", "Lift Rock", "Under leaves"),
	step(wb(cps)("SW super")),
	Korok("C27", "Race", "Start on wall SQ DEFUSE"),
	step(wb(cps)("SW super")),
	Korok("C31", "Lift Rock", "On wall"),
	step(wb(cps)("NW")),
	ShrineSword("Katah Chuki"),
	split("-"),
];