import { Boss, Discover, fury, Koroks, MakeMorning, Materials, Npc, Shrines, Towers, WindbombStepCps } from "../../engine";

export const HyruleRidge = [
	WindbombStepCps("GALE + W midairs").extend({
		ability: { gale: 1 },
	}),
	Koroks.R06,
	WindbombStepCps("W>"),
	Koroks.R09,
	WindbombStepCps("<S DT"),
	Towers.Ridgeland(),
	WindbombStepCps("W Turn"),
	Koroks.R15,
	WindbombStepCps("<S SQ"),
	Koroks.R18,
	WindbombStepCps("<W Turn"),
	"Start flower chase",
	Koroks.R24,
	Koroks.R23,
	WindbombStepCps("<N"),
	"Red orb",
	WindbombStepCps("NW"),
	"Orange orb",
	WindbombStepCps("NW"),
	Koroks.R08,
	WindbombStepCps("<S Turn"),
	Koroks.R14,
	WindbombStepCps("N"),
	"Green orb",
	Shrines.TohYahsa,

	WindbombStepCps("W midairs"),
	Koroks.R13,
	"Cryo down",
	Materials.HeartyBass(5, "Shock"),
	WindbombStepCps("S"),
	Koroks.R17,
	WindbombStepCps("<<S Turn"),
	Koroks.R30,
	WindbombStepCps("<E Turn"),
	Koroks.R31,
	Boss("Blue Hinox", fury()).extend({
		ability: { fury: 3 }
	}),
	Koroks.R22,
	WindbombStepCps("W Turn"),
	Koroks.R21,
	WindbombStepCps("W"),
	Shrines.ShaeLoya,

	Npc("Keeha Yoog Man", "8AM to midnight"),
	MakeMorning("For Dinraal (Claw)"),
	Npc("Fairy Fountain Guy", "Twice"),
	WindbombStepCps("SQ to bridge"),
	Koroks.T34,
	WindbombStepCps("S> Turn"),
	Koroks.R28,
	WindbombStepCps("E"),
	Koroks.R29,
	WindbombStepCps("N"),
	Koroks.R20,
	Materials.Dinraal(1),
	Discover("Tabantha Canyon Course"),
	WindbombStepCps("N. Turn"),
	Koroks.R12
];