import { step, Korok, ability, Boss, VariableChange, detail, Discover, Shrine, split, Snap, MakeTOD, ShrineBlessing, Section, Warp } from "../create";
import { cps, fury, gale, important, itm, npc, txt, v } from "../types";
import { wb } from "../windbomb";

export const Kakariko2 = [
	Section("KAKARIKO 2"),
	Warp("Dueling Peaks Tower", txt("Check ", v("krk"), " Koroks")),
	split("{Cenladup Faroluheve}"),

	step(wb(cps)("NW")),
	Korok("D25", "Jump Fence", "Summon Horse"),
	step(wb(cps)("<E Turn>")),
	Korok("D16", "Lift Rock", "Small island"),
	step(wb(cps)("S> Turn")),
	Korok("D29", "Lift Rock", "On island"),
	step(wb(cps)("W")),
	Korok("D28", "Confetti", "Top of flagpole"),
	step(wb(cps)("NW")),
	Korok("D23", "Acorn Flying"),
	step(wb(cps)("E")),
	Korok("D24", "Boulder Golf", "Surf down after bomb"),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("N.")),
	Korok("D15", "Tree Stump", "Edge of forest"),
	step(wb(cps)("E>")),
	Korok("D13", "Lift Rock (Tree)", "3rd big tree N of open rock"),
	step(wb(cps)("NE")),
	Discover("Horwell Bridge"),
	"Midair to shrine",
	Shrine("Hila Rao"),
	split("-"),

	step(npc("Talk to Flowerblight")),
	step(wb(cps)("SE")),
	Discover("Eagus Bridge"),
	Korok("D01", "Lift Rock", "Island below"),
	step(wb(cps)("N> super")),
	Korok("Z47", "Lift Rock Blocked", "Under boulder"),
	step(wb(cps)("<E Turn")),
	Korok("Z48", "Light Chase"),
	step("SQ to 3 trees"),
	Korok("Z49", "Match Tree", "left tree"),
	step(wb(cps)("E>")),
	Korok("Z50", "Light Chase"),
	step(wb(cps)("S> no turn")),
	Korok("Z60", "Offer Apple", "In cave"),
	itm("Bass until 15"),
	step(wb(cps)("<E + NE")),
	Korok("N01", "Lift Rock (Tree)"),
	ability(step(gale(), " + ", wb(cps)("S midairs")), {gale: 1}),
	VariableChange({silentPrincess: 3}),
	detail(
		itm("3 Silent Princess"),
		txt(v("silentPrincess"), "/19")),
	npc("Activate Fairy Fountain"),
	detail(
		Snap("Fairy Fountain", "SNAP Quest"),
		important("DO NOT FORGET. DO NOT FORGET. DO NOT FORGET")),
	MakeTOD("12pm", "Make 11AM-3PM", "No rain"),
	step(wb(cps)("<W Turn")),
	"2 Cucoos",
	npc("Tag with Cottla (12)"),
	"Run back",
	npc("Catch Cottla"),
	"3 Cucoos",
	npc("Fairy Fountain Guy x2"),
	"1 Cucoo",
	"Shoot torches with GEB",
	detail(
		npc("Cook Boy 4 Quests"),
		"Buy carrot if don't have. Last food is energetic"),
	MakeTOD("9pm", "Make Night"),
	important("EQUIP STEALTH"),
	VariableChange({beetle: 1}),
	detail(
		itm("Beetle"),
		txt(v("beetle"), "/15")),
	detail(
		npc("Fire Lady"),
		"Can buy arrows if need"),
	"Last Cucoo",
	npc("Cucoo Guy"),
	itm("Fireflies"),
	detail(
		npc("Firefly Lady Twice"),
		"Talk again after she sits down"),
	"Put 5 fireflies",
	"WB to Impa",
	npc("Impa"),
	npc("Paya"),
	MakeTOD("9pm", "Make Night"),
	step(Korok("D03", "Offer Apple")),
	Korok("D02", "Lily Pads", "Impa house. Cryo"),
	ability(step(gale(), " + ", wb(cps)("<S")), {gale: 1}),
	Korok("D04", "Lift Rock", "Ledge"),
	Korok("D05", "Shoot Emblem"),
	step(wb(cps)("E")),
	Korok("D08", "Lift Rock", "On ledge"),
	Korok("D06", "Shoot Emblem"),
	step(wb(cps)("E> Turn")),
	Korok("D12", "Block Puzzle"),
	step(wb(cps)("<N")),
	VariableChange({beetle: 1}),
	detail(
		itm("Beetle"),
		txt(v("beetle"), "/15")),
	"Climb up gate",
	step(wb(cps)("N + NE")),
	Korok("N07", "Match Tree", "Bomb left"),
	"Surf down",
	Korok("N08", "Block Puzzle"),
	step(wb(cps)("E")),
	Korok("N10", "Flower Chase"),
	step(wb(cps)("E + W")),
	Korok("N09", "Offer Apple"),
	ability(step(gale(), " + ", wb(cps)("S + S midair")), {gale: 1}),
	Korok("D07", "Lift Rock", "2nd Peak"),
	step(wb(cps)("SW")),
	Korok("D11", "Lift Rock", "Peak"),
	step(wb(cps)("W")),
	Korok("D10", "Lift Rock", "2nd Peak"),
	Korok("D09", "Match Tree", "Closest to peak"),
	step(wb(cps)("N> Turn")),
	VariableChange({silentPrincess: 3}),
	detail(
		itm("3 Silent Princess"),
		txt(v("silentPrincess"), "/19. If you are 2 short you can grab last 2 at last fairy fountain.")),
	step(wb(cps)("SE")),
	"MS Blade Master",
	ShrineBlessing("Lakna Rokee"),
	split("-"),

];