import { cps, Discover, important, Item, itm, Koroks, Npc, npc, Shop, Shrines, SnapQuest, STEP, Warp, wb } from "../../engine";

export const Lotus = [
	Warp("Taloh Naeg"),
	{ type: STEP, text: "SQ to farmer" },
	Npc("Pumpkin Man"),
	{ type: STEP, text: "SQ to shops" },
	Shop("Arrows"),
	Shop("Carrots"),
	Npc("Impa"),
	{ type: STEP, text: wb(cps)("<<E") },
	itm("4 Fairies"),
	Npc("Fairy Fountain"),
	SnapQuest("Fairy Fountain"),
	{ type: STEP, text: wb(cps)("N Super") },
	Koroks.N01,
	{ type: STEP, text: wb(cps)("SW Super") },
	Koroks.Z60,
	important("EAT SPEED"),
	{ type: STEP, text: wb(cps)("N>>") },
	Koroks.Z50,
	{ type: STEP, text: wb(cps)("<N Turn") },
	Shrines.DakaTuss,
	{ type: STEP, text: wb(cps)("<W Turn") },
	Koroks.Z49,
	{ type: STEP, text: wb(cps)("W> SQ") },
	Koroks.Z48,
	{ type: STEP, text: wb(cps)("<W Turn") },
	Koroks.Z47,
	{ type: STEP, text: wb(cps)("N>> Turn") },
	Koroks.Z38,
	{ type: STEP, text: wb(cps)("SE") },
	Discover("Goponga Village Ruins"),
	{ type: STEP, text: wb(cps)("N Midair") },
	"Start farming Lotus",
	Koroks.Z40,
	Item("30+ Lotus"),
    
];