import { ability, Boss, Chest, detail, Discover, Korok, MakeTOD, Memory, Shop, Shrine, Snap, split, step, VariableChange } from "../create";
import { cps, txt, fury, npc, itm, v, important, gale } from "../types";
import { wb } from "../windbomb";

export const Hateno2 = [
	step(wb(cps)("S + SE super")),
	Korok("N28", "Offer Apple"),
	Shrine("Kam Urog"),
	split("-"),

	detail(
		step(wb(cps)("S + SW super/midair")),
		"Same as AS movement. Stalnox despawns at 4AM. If miss: make night before entering toto sah and kill it after"),
	ability(Boss("Stalnox", txt("GEB + ", fury())), {fury: 3}),
	step(wb(cps)(".S")),
	Chest("Sapphire", "In cave for quest"),
	Korok("D59", "Lift Rock", "Bottom of waterfall"),
	step("SQ to shrine"),
	Shrine("Toto Sah"), 
	split("-"),

	step("Cryo + run out"),
	Korok("D56", "Lift Rock", "Tree stump"),
	step(wb(cps)("<N + W")),
	Korok("D55", "Lift Rock", "On ledge high"),
	step(wb(cps)("N. Turn down")),
	Discover("Little Twin Bridge"),
	"SQ DEFUSE",
	Discover("Big Twin Bridge"),
	"SQ to shrine",
	Shrine("Ha Dahamar"),
	split("-"),

	step(wb(cps)("E to top")),
	Korok("D42", "Confetti", "Top of stable"),
	step("SQ to horse"),
	"Ride near stable",
	detail(
		Shop("Beedle", "Frogs/Crickets if need"),
		"DO NOT GIVE HIM BEETLE"),
	npc("Horse Catching Guy Twice (B)"),
	npc("Two Guys Inside Twice"),
	step(wb(cps)("SE")),
	Korok("D51", "Lift Rock (Tree)", "Big tree"),
	step(wb(cps)("E> Turn")),
	Korok("D52", "Balloon"),
	step(wb(cps)("<N Turn")),
	Memory("Ash Swamp"),
	split("-"),
	step(wb(cps)("<E Turn")),
	VariableChange({rushroom: 3}),
	detail(
		itm("3 Rushrooms"),
		txt(v("rushroom"), "/55")),
	Korok("N33", "Lift Rock (Door)"),
	MakeTOD("5am", "Make Morning", "If past 6AM"),
	VariableChange({honey: 2}),
	detail(
		itm("2 Honey"),
		txt(v("honey"), "/16")),
	important("CHECK 15 Honey"),
	npc("Doctor (B)"),
	ability(step(gale(), " up fort"), {gale: 1}),
	Korok("N34", "Acorn Flying"),
	step(wb(cps)(".N")),
	Korok("N27", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("N>")),
	Korok("N26", "Boulder Golf"),
	step(wb(cps)("<S Turn")),
	detail(
		ability(Boss("Stone Talus", fury()), {fury: 1}),
		"Can fury from edge of mountain"),
	"Run down",
	Korok("N35", "Block Puzzle"),
	step(wb(cps)(".E Turn")),
	Korok("N36", "Acorn", "In tree"),
	step(wb(cps)("<E")),
	Korok("N37", "Lily Pads", "Cryo block"),
	step(wb(cps)("S")),
	Korok("N38", "Balloon"),
	step("SQ to stone left of talus"),
	ability(Boss("Stone Talus", fury()), {fury: 1}),
	step(wb(cps)("<W Turn")),
	Korok("N41", "Lily Pads", "Cryo block"),
	step(wb(cps)("<W")),
	detail(
		"Shoot 10 Targets",
		"2 on upper lane, then 3 leading to house, 3 more leading to last 2"),
	Korok("N45", "Balloon"),
	"Run",
	Korok("N46", "Lift Rock (Door)"),
	step(wb(cps)("NE")),
	Korok("N51", "Lift Rock", "Side of lake"),
	step(wb(cps)("E")),
	Korok("N52", "Acorn", "In tree"),
	step(wb(cps)("E>")),
	Korok("N53", "Lift Rock"),
	ability(gale(), {gale: 1}),
	npc("Invite Bolson"),
	"SQ to weapon boy",
	detail(
		npc("Weapon Boy"),
		"Get Diamond"),
	Shop("Bomb Arrows", "if need"),
	detail(
		Shop("Sell Rubber Helm"),
		"If you didn't pick up extra armor. You should have 25 + the 7 upgrade ones. This helps with menuing and gives 600k"),
	Shop("Sell Material", "2nd Option"),
	"Core = 54.9K",
	detail(
		"Sh Ge = 51.5K",
		"12.3K before selling shaft"),
	detail(
		"Sh Sc Sp = 51.5K",
		"25.5K before selling screws + springs"),
	detail(
		"Sh Sc = 43.5K",
		"32K before selling screws"),
	detail(
		"Sh Sp = 43.5K",
		"29K before selling springs"),
	npc("Shrine Quest Lady"),
	npc("Cricket Guy"),
	npc("Cricket Lady"),
	npc("Cricket Guy Twice"),
	step(wb(cps)("E")),
	npc("Sheep Lady"),
	step(wb(cps)("E")),
	npc("Picture Guy"),
	Snap("Sunshroom","SNAP Quest"),
	npc("Picture Guy 1st option"),
	"Buy all pictures"
];