import { ability, Boss, ChestSpecial, detail, Discover, Korok, MakeTOD, split, step, Tower, VariableChange } from "../create";
import { cps, txt, gale, important, emy, itm, v, fury } from "../types";
import { wb } from "../windbomb";

export const LakeTower = [
	step(wb(cps)(".E Turn")),
	Korok("D27", "Lift Rock", "Under bridge"),
	step("SQ"),
	Korok("D34", "Lift Rock"),
	Korok("D33", "Block Puzzle"),
	step(cps("W")),
	Korok("D32", "Basketball", "GG throw p close"),
	step(wb(cps)("S")),
	Korok("D31", "Boulder Golf"),
	step(wb(cps)("S>")),
	MakeTOD("9pm", "Make Night"),
	Korok("D44", "Lift Rock"),
	step(wb(cps)("<W Turn")),
	Korok("P12", "Lift Rock (Door)"),
	"Drop",
	Korok("P13", "Lift Rock (Door)"),
	step(wb(cps)("N> Turn")),
	Discover("Outpost Ruins"),
	VariableChange({rushroom: 7}),
	detail(
		itm("7 Rushrooms"),
		txt(v("rushroom"), "/55")),
	step(wb(cps)("S")),
	ability(Boss("Luminous Talus", fury()), {fury: 3}),
	important("BURN OUT FURY"),
	step("SQ ", cps("S")),
	Korok("D43", "Flower Count", "In cave"),
	step(wb(cps)("<S + E>")),
	Korok("L03", "Block Puzzle",),
	step(wb(cps)("<S Turn")),
	"Place cryo block",
	Korok("L10", "Lily Pads", "No Drown"),
	step(wb(cps)("W + W")),
	Korok("D54", "Torch"),
	"Drop down",
	Korok("L09", "Basketball"),
	"Drop down",
	Korok("L15", "Balloon", "In pillar"),
	Korok("L14", "Lift Rock Blocked", "Under slab (STS a lot)"),
	step(wb(cps)("S")),
	Korok("L26", "Tree Branch"),
	"Climb up",
	important("LOOK SKY SOUTH"),
	Korok("L27", "Confetti", "Top of fountain"),
	"Watch chest land",
	"Run to flower",
	Korok("L30", "Flower Chase"),
	"Drop down",
	Korok("L31", "Lift Rock"),
	step(cps("E")),
	Korok("L32", "Metal Box Circle"),
	step(wb(cps)("SW")),
	ChestSpecial("Xenoblade Chest"),
	step("SQ ", cps("<S")),
	Korok("L39", "Lift Rock"),
	step(cps("E")),
	Korok("L40", "Acorn", "In tree"),
	step(cps("<W")),
	Korok("L42", "Boulder Golf", "Bomb in"),
	"Surf down",
	Korok("L43", "Light Chase"),
	step(wb(cps)("SW")),
	Korok("L51", "Boulder Golf", "2 STS + bomb in"),
	step(cps("W")),
	txt("Kill 2 archer ", emy("Lizalfos")),
	VariableChange({rushroom: 8}),
	detail(
		itm("8 Rushrooms"),
		txt("Knock down with blizzard rod. ", v("rushroom"), "/55")),
	ability(step(cps("W"), " + ", gale()), {gale: 1}),
	Tower("Lake Tower"),
	split("-"),
    
];