import { ability, Boss, detail, Korok, Memory, Shrine, split, step, VariableChange } from "../create";
import { cps, fury, itm, txt, v } from "../types";
import { wb } from "../windbomb";

export const ReeDahee = [
	step(Korok("L53", "Tree Stump", "Left next to shrine")),
	"Surf + run to flower",
	Korok("L55", "Flower Chase"),
	step(wb(cps)("W>> Turn")),
	Korok("L44", "Boulder Golf"),
	step(wb(cps)(".N Turn")),
	Korok("L33", "Balloon"),
	step(wb(cps)("N")),
	Korok("L16", "Boulder Golf", "Bomb down stasis"),
	step(wb(cps)("<N")),
	Korok("L11", "Tree Stump"),
	step(wb(cps)("N to tree stump")),
	VariableChange({rushroom: 5}),
	detail(
		itm("5 Rushrooms"),
		txt("Land on top and knock down with blizzard rod. ", v("rushroom"), "/55")),
	Korok("L05", "Flower Chase"),
	"Surf down",
	Korok("L06", "Light Chase"),
	step(wb(cps)("NW")),
	Korok("L02", "Lift Rock", "In big tree stump"),
	"Run/SQ",
	detail(
		ability(Boss("Stone Talus", fury()), {fury: 1}),
		"Fury from well korok"),
	Korok("L01", "Well"),
	step(wb(cps)("S>>")),
	Korok("L04", "Tree Stump"),
	step(wb(cps)(".N Turn")),
	Memory("West Necluda"),
	split("-"),

	step(Korok("D45", "Confetti")),
	step(wb(cps)("NE")),
	Korok("D35", "Balloon"),
	step(wb(cps)("<E Turn")),
	Korok("D36", "Flower Chase"),
	step(wb(cps)("<S")),
	Korok("D46", "Match Tree", "Right tree"),
	step(wb(cps)("N> Turn")),
	Korok("D37", "Boulder Golf"),
	Korok("D38", "Lift Rock", "In cave"),
	step(wb(cps)("E> No Turn")),
	Korok("D47", "Balloon"),
	step(wb(cps)("<E Turn")),
	Korok("D39", "Flower Chase", "Across River"),
	step(wb(cps)("W. Turn")),
	Shrine("Ree Dahee"),
	split("-"),
];