import { step, Korok, Boss, ChestSpecial, Discover, Shrine, split, ability, detail, MakeTOD } from "../create";
import { cps, fury, gale, important, itm, npc, rne, txt } from "../types";
import { wb } from "../windbomb";

export const KaoMakagh = [
	step(wb(cps)("W")),
	Korok("L13", "Lift Rock Blocked", "Under rubble"),
	step(wb(cps)("<W Turn")),
	detail(
		Korok("L17", "Light Chase"),
		"L17 and L18 are at the same location"),
	Korok("L18", "Light Chase"),
	step("SQ ", cps("N>"), " down"),
	Korok("L12", "Block Puzzle", "Piece on tree"),
	ability(step(gale(), " + ", cps("S")), {gale: 1}),
	Korok("L28", "Flower Count", "On peak"),
	step(wb(cps)("E")),
	Korok("L29", "Lift Rock", "Peak"),
	step(wb(cps)("E> Turn")),
	Korok("L34", "Boulder Circle", "STS Jump ATK down"),
	step(wb(cps)("<W")),
	Korok("L35", "Match Tree",txt("Right, ", "2 durians")),
	step(wb(cps)("S no turn")),
	Korok("L45", "Lift Rock"),
	step("SQ to creek DEFUSE"),
	Korok("L54", "Lily Pads", "No Drown"),
	step(wb(cps)("E")),
	Discover("Zonai Ruins"),
	Korok("L56", "Boulder Circle", rne("STS + Magnesis")),
	txt("SQ to ", npc("Kass")),
	"Run up",
	Korok("L57", "Light Chase"),
	step(wb(cps)("S>")),
	Korok("L61", "Lift Rock Blocked", "Under slab (1 STS hit)"),
	"Run",
	Korok("L66", "Basketball", "Cryo block"),
	step(wb(cps)("E> + E> to pillar")),
	Korok("L72", "Race", wb(cps)("N> Turn")),
	step(wb(cps)("S + S")),
	Korok("L78", "Lift Rock", "Peak"),
	"Surf down",
	ChestSpecial("Ancient Saddle"),
	txt(npc("Horse God")),
	step(cps("W")),
	Korok("L77", "Rock Circle"),
	step(wb(cps)(".W Turn")),
	Korok("L91", "Rock Circle"),
	step(wb(cps)("N")),
	Korok("L76", "Boulder Golf", "Stasis 2 + BTMA"),
	"Run",
	Discover("Horse God Bridge"),
	step(wb(cps)("N> Turn. Land+cryo block")),
	Korok("L75", "Lily Pads", "No Drown"),
	step(wb(cps)(".N Turn")),
	ability(txt(fury(), " Kill Bokos"), {fury: 3}),
	txt("Turn in ", npc("Quest")),
	"Take out horse",
	npc("HORSE MINIGAMES"),
	"1:30 and 1:15",
	txt("Put on ", itm("Ancient Saddle"), "(3)"),
	MakeTOD("9pm", "Make Night", "For stanox"),
	step(cps("N")),
	Shrine("Ka'o Makagh"),
	split("-"),
];